// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getClustersInTower (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        crystals_0_0_read,
        crystals_0_1_read,
        crystals_0_2_read,
        crystals_0_3_read,
        crystals_0_4_read,
        crystals_1_0_read,
        crystals_1_1_read,
        crystals_1_2_read,
        crystals_1_3_read,
        crystals_1_4_read,
        crystals_2_0_read,
        crystals_2_1_read,
        crystals_2_2_read,
        crystals_2_3_read,
        crystals_2_4_read,
        crystals_3_0_read,
        crystals_3_1_read,
        crystals_3_2_read,
        crystals_3_3_read,
        crystals_3_4_read,
        crystals_4_0_read,
        crystals_4_1_read,
        crystals_4_2_read,
        crystals_4_3_read,
        crystals_4_4_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 6'b1;
parameter    ap_ST_fsm_pp0_stage1 = 6'b10;
parameter    ap_ST_fsm_pp0_stage2 = 6'b100;
parameter    ap_ST_fsm_pp0_stage3 = 6'b1000;
parameter    ap_ST_fsm_pp0_stage4 = 6'b10000;
parameter    ap_ST_fsm_pp0_stage5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_2 = 3'b10;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] crystals_0_0_read;
input  [15:0] crystals_0_1_read;
input  [15:0] crystals_0_2_read;
input  [15:0] crystals_0_3_read;
input  [15:0] crystals_0_4_read;
input  [15:0] crystals_1_0_read;
input  [15:0] crystals_1_1_read;
input  [15:0] crystals_1_2_read;
input  [15:0] crystals_1_3_read;
input  [15:0] crystals_1_4_read;
input  [15:0] crystals_2_0_read;
input  [15:0] crystals_2_1_read;
input  [15:0] crystals_2_2_read;
input  [15:0] crystals_2_3_read;
input  [15:0] crystals_2_4_read;
input  [15:0] crystals_3_0_read;
input  [15:0] crystals_3_1_read;
input  [15:0] crystals_3_2_read;
input  [15:0] crystals_3_3_read;
input  [15:0] crystals_3_4_read;
input  [15:0] crystals_4_0_read;
input  [15:0] crystals_4_1_read;
input  [15:0] crystals_4_2_read;
input  [15:0] crystals_4_3_read;
input  [15:0] crystals_4_4_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] ap_CS_fsm_pp0_stage5;
reg   [15:0] crystals_4_0_read_1_reg_668;
reg   [15:0] crystals_1_0_read_1_reg_673;
wire   [15:0] tmp5_fu_256_p2;
reg   [15:0] tmp5_reg_678;
wire   [15:0] tmp8_fu_262_p2;
reg   [15:0] tmp8_reg_683;
wire   [15:0] tmp17_fu_268_p2;
reg   [15:0] tmp17_reg_688;
wire   [15:0] tmp23_fu_274_p2;
reg   [15:0] tmp23_reg_693;
wire   [15:0] tmp32_fu_280_p2;
reg   [15:0] tmp32_reg_698;
reg   [15:0] crystals_3_0_read_1_reg_703;
wire   [0:0] ap_CS_fsm_pp0_stage1;
reg   [15:0] crystals_2_0_read_1_reg_708;
reg   [15:0] crystals_0_0_read_1_reg_713;
wire   [15:0] phiStripSum_0_fu_297_p2;
reg   [15:0] phiStripSum_0_reg_718;
wire   [15:0] phiStripSum_1_fu_314_p2;
reg   [15:0] phiStripSum_1_reg_724;
wire   [15:0] tmp11_fu_320_p2;
reg   [15:0] tmp11_reg_730;
wire   [15:0] tmp14_fu_326_p2;
reg   [15:0] tmp14_reg_735;
wire   [15:0] phiStripSum_4_fu_343_p2;
reg   [15:0] phiStripSum_4_reg_740;
wire   [15:0] tmp20_fu_349_p2;
reg   [15:0] tmp20_reg_746;
wire   [15:0] etaStripSum_1_fu_365_p2;
reg   [15:0] etaStripSum_1_reg_751;
reg   [15:0] ap_pipeline_reg_pp0_iter1_etaStripSum_1_reg_751;
wire   [15:0] tmp26_fu_371_p2;
reg   [15:0] tmp26_reg_759;
wire   [15:0] tmp29_fu_377_p2;
reg   [15:0] tmp29_reg_764;
wire   [15:0] etaStripSum_4_fu_393_p2;
reg   [15:0] etaStripSum_4_reg_769;
reg   [15:0] ap_pipeline_reg_pp0_iter1_etaStripSum_4_reg_769;
wire   [15:0] phiStripSum_2_fu_410_p2;
reg   [15:0] phiStripSum_2_reg_777;
wire   [0:0] ap_CS_fsm_pp0_stage2;
wire   [15:0] phiStripSum_3_fu_427_p2;
reg   [15:0] phiStripSum_3_reg_783;
wire   [15:0] etaStripSum_0_fu_443_p2;
reg   [15:0] etaStripSum_0_reg_789;
wire   [15:0] etaStripSum_2_fu_459_p2;
reg   [15:0] etaStripSum_2_reg_796;
wire   [15:0] etaStripSum_3_fu_475_p2;
reg   [15:0] etaStripSum_3_reg_804;
wire   [15:0] tmp35_fu_481_p2;
reg   [15:0] tmp35_reg_812;
wire   [15:0] tmp_42_4_fu_493_p2;
reg   [15:0] tmp_42_4_reg_817;
wire   [0:0] ap_CS_fsm_pp0_stage3;
wire   [2:0] grp_getPeakBinOf5_fu_236_ap_return;
reg   [2:0] tmp_s_reg_824;
wire   [2:0] grp_getPeakBinOf5_fu_246_ap_return;
reg   [2:0] peakPhi_write_assign_reg_836;
wire   [3:0] tmp_46_cast_cast_fu_499_p1;
reg   [3:0] tmp_46_cast_cast_reg_841;
wire   [3:0] eta_3_fu_503_p2;
reg   [3:0] eta_3_reg_846;
wire   [15:0] clusterET_1_fu_541_p3;
reg   [15:0] clusterET_1_reg_851;
wire   [0:0] tmp_48_1_fu_549_p2;
reg   [0:0] tmp_48_1_reg_856;
wire   [15:0] tmp_50_1_fu_564_p2;
reg   [15:0] tmp_50_1_reg_861;
wire   [0:0] tmp_48_2_fu_575_p2;
reg   [0:0] tmp_48_2_reg_866;
wire   [15:0] newSel2_fu_614_p3;
reg   [15:0] newSel2_reg_871;
reg    ap_enable_reg_pp0_iter0_preg;
reg   [15:0] ap_port_reg_crystals_0_0_read;
reg   [15:0] ap_port_reg_crystals_0_1_read;
reg   [15:0] ap_port_reg_crystals_0_2_read;
reg   [15:0] ap_port_reg_crystals_0_3_read;
reg   [15:0] ap_port_reg_crystals_0_4_read;
reg   [15:0] ap_port_reg_crystals_1_2_read;
reg   [15:0] ap_port_reg_crystals_1_3_read;
reg   [15:0] ap_port_reg_crystals_2_0_read;
reg   [15:0] ap_port_reg_crystals_2_1_read;
reg   [15:0] ap_port_reg_crystals_2_2_read;
reg   [15:0] ap_port_reg_crystals_2_3_read;
reg   [15:0] ap_port_reg_crystals_2_4_read;
reg   [15:0] ap_port_reg_crystals_3_0_read;
reg   [15:0] ap_port_reg_crystals_3_1_read;
reg   [15:0] ap_port_reg_crystals_3_2_read;
reg   [15:0] ap_port_reg_crystals_3_3_read;
reg   [15:0] ap_port_reg_crystals_3_4_read;
reg   [15:0] ap_port_reg_crystals_4_2_read;
reg   [15:0] ap_port_reg_crystals_4_3_read;
wire    grp_getPeakBinOf5_fu_236_ap_start;
wire    grp_getPeakBinOf5_fu_236_ap_done;
wire    grp_getPeakBinOf5_fu_236_ap_idle;
wire    grp_getPeakBinOf5_fu_236_ap_ready;
wire    grp_getPeakBinOf5_fu_246_ap_start;
wire    grp_getPeakBinOf5_fu_246_ap_done;
wire    grp_getPeakBinOf5_fu_246_ap_idle;
wire    grp_getPeakBinOf5_fu_246_ap_ready;
reg    ap_reg_grp_getPeakBinOf5_fu_236_ap_start;
wire   [0:0] ap_CS_fsm_pp0_stage4;
reg    ap_reg_grp_getPeakBinOf5_fu_246_ap_start;
wire   [15:0] tmp_fu_286_p2;
wire   [15:0] tmp6_fu_292_p2;
wire   [15:0] tmp7_fu_303_p2;
wire   [15:0] tmp9_fu_309_p2;
wire   [15:0] tmp16_fu_332_p2;
wire   [15:0] tmp18_fu_338_p2;
wire   [15:0] tmp22_fu_355_p2;
wire   [15:0] tmp24_fu_361_p2;
wire   [15:0] tmp31_fu_383_p2;
wire   [15:0] tmp33_fu_389_p2;
wire   [15:0] tmp10_fu_399_p2;
wire   [15:0] tmp12_fu_405_p2;
wire   [15:0] tmp13_fu_416_p2;
wire   [15:0] tmp15_fu_422_p2;
wire   [15:0] tmp19_fu_433_p2;
wire   [15:0] tmp21_fu_439_p2;
wire   [15:0] tmp25_fu_449_p2;
wire   [15:0] tmp27_fu_455_p2;
wire   [15:0] tmp28_fu_465_p2;
wire   [15:0] tmp30_fu_471_p2;
wire   [15:0] tmp34_fu_485_p2;
wire   [15:0] tmp36_fu_489_p2;
wire   [0:0] tmp_17_fu_509_p2;
wire   [0:0] tmp_18_fu_514_p2;
wire   [2:0] tmp_19_fu_530_p6;
wire   [0:0] or_cond_4_fu_519_p2;
wire   [15:0] tmp_19_fu_530_p7;
wire   [15:0] tmp_20_fu_554_p7;
wire   [3:0] eta_3_2_fu_570_p2;
wire   [0:0] sel_tmp4_fu_591_p2;
wire   [0:0] sel_tmp2_fu_586_p2;
wire   [0:0] sel_tmp_fu_581_p2;
wire   [0:0] or_cond_fu_602_p2;
wire   [15:0] newSel_fu_596_p3;
wire   [15:0] newSel1_fu_608_p3;
wire   [15:0] clusterET_1_1_fu_622_p3;
wire   [15:0] tmp_50_2_fu_627_p2;
wire   [15:0] mrv_trunc_ext_fu_639_p1;
wire   [15:0] mrv_1_trunc_ext_fu_648_p1;
wire   [15:0] clusterET_1_2_fu_632_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_pipeline_idle_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'b1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_preg = 1'b0;
#0 ap_reg_grp_getPeakBinOf5_fu_236_ap_start = 1'b0;
#0 ap_reg_grp_getPeakBinOf5_fu_246_ap_start = 1'b0;
end

getPeakBinOf5 grp_getPeakBinOf5_fu_236(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_getPeakBinOf5_fu_236_ap_start),
    .ap_done(grp_getPeakBinOf5_fu_236_ap_done),
    .ap_idle(grp_getPeakBinOf5_fu_236_ap_idle),
    .ap_ready(grp_getPeakBinOf5_fu_236_ap_ready),
    .et_0_read(etaStripSum_0_reg_789),
    .et_1_read(etaStripSum_1_reg_751),
    .et_2_read(etaStripSum_2_reg_796),
    .et_3_read(etaStripSum_3_reg_804),
    .et_4_read(etaStripSum_4_reg_769),
    .etSum(tmp_42_4_reg_817),
    .ap_return(grp_getPeakBinOf5_fu_236_ap_return)
);

getPeakBinOf5 grp_getPeakBinOf5_fu_246(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_getPeakBinOf5_fu_246_ap_start),
    .ap_done(grp_getPeakBinOf5_fu_246_ap_done),
    .ap_idle(grp_getPeakBinOf5_fu_246_ap_idle),
    .ap_ready(grp_getPeakBinOf5_fu_246_ap_ready),
    .et_0_read(phiStripSum_0_reg_718),
    .et_1_read(phiStripSum_1_reg_724),
    .et_2_read(phiStripSum_2_reg_777),
    .et_3_read(phiStripSum_3_reg_783),
    .et_4_read(phiStripSum_4_reg_740),
    .etSum(tmp_42_4_reg_817),
    .ap_return(grp_getPeakBinOf5_fu_246_ap_return)
);

getClustersInCardbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
getClustersInCardbkb_U7(
    .din1(etaStripSum_0_reg_789),
    .din2(ap_pipeline_reg_pp0_iter1_etaStripSum_1_reg_751),
    .din3(etaStripSum_2_reg_796),
    .din4(etaStripSum_3_reg_804),
    .din5(ap_pipeline_reg_pp0_iter1_etaStripSum_4_reg_769),
    .din6(tmp_19_fu_530_p6),
    .dout(tmp_19_fu_530_p7)
);

getClustersInCardbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
getClustersInCardbkb_U8(
    .din1(etaStripSum_0_reg_789),
    .din2(ap_pipeline_reg_pp0_iter1_etaStripSum_1_reg_751),
    .din3(etaStripSum_2_reg_796),
    .din4(etaStripSum_3_reg_804),
    .din5(ap_pipeline_reg_pp0_iter1_etaStripSum_4_reg_769),
    .din6(tmp_s_reg_824),
    .dout(tmp_20_fu_554_p7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_preg <= 1'b0;
    end else begin
        if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
            ap_enable_reg_pp0_iter0_preg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & ~(1'b1 == ap_enable_reg_pp0_iter0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_getPeakBinOf5_fu_236_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_reg_grp_getPeakBinOf5_fu_236_ap_start <= 1'b1;
        end else if ((1'b1 == grp_getPeakBinOf5_fu_236_ap_ready)) begin
            ap_reg_grp_getPeakBinOf5_fu_236_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_getPeakBinOf5_fu_246_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_reg_grp_getPeakBinOf5_fu_246_ap_start <= 1'b1;
        end else if ((1'b1 == grp_getPeakBinOf5_fu_246_ap_ready)) begin
            ap_reg_grp_getPeakBinOf5_fu_246_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
        ap_pipeline_reg_pp0_iter1_etaStripSum_1_reg_751 <= etaStripSum_1_reg_751;
        ap_pipeline_reg_pp0_iter1_etaStripSum_4_reg_769 <= etaStripSum_4_reg_769;
        crystals_0_0_read_1_reg_713 <= ap_port_reg_crystals_0_0_read;
        crystals_2_0_read_1_reg_708 <= ap_port_reg_crystals_2_0_read;
        crystals_3_0_read_1_reg_703 <= ap_port_reg_crystals_3_0_read;
        etaStripSum_1_reg_751 <= etaStripSum_1_fu_365_p2;
        etaStripSum_4_reg_769 <= etaStripSum_4_fu_393_p2;
        eta_3_reg_846 <= eta_3_fu_503_p2;
        peakPhi_write_assign_reg_836 <= grp_getPeakBinOf5_fu_246_ap_return;
        phiStripSum_0_reg_718 <= phiStripSum_0_fu_297_p2;
        phiStripSum_1_reg_724 <= phiStripSum_1_fu_314_p2;
        phiStripSum_4_reg_740 <= phiStripSum_4_fu_343_p2;
        tmp11_reg_730 <= tmp11_fu_320_p2;
        tmp14_reg_735 <= tmp14_fu_326_p2;
        tmp20_reg_746 <= tmp20_fu_349_p2;
        tmp26_reg_759 <= tmp26_fu_371_p2;
        tmp29_reg_764 <= tmp29_fu_377_p2;
        tmp_46_cast_cast_reg_841[2 : 0] <= tmp_46_cast_cast_fu_499_p1[2 : 0];
        tmp_s_reg_824 <= grp_getPeakBinOf5_fu_236_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        ap_port_reg_crystals_0_0_read <= crystals_0_0_read;
        ap_port_reg_crystals_0_1_read <= crystals_0_1_read;
        ap_port_reg_crystals_0_2_read <= crystals_0_2_read;
        ap_port_reg_crystals_0_3_read <= crystals_0_3_read;
        ap_port_reg_crystals_0_4_read <= crystals_0_4_read;
        ap_port_reg_crystals_1_2_read <= crystals_1_2_read;
        ap_port_reg_crystals_1_3_read <= crystals_1_3_read;
        ap_port_reg_crystals_2_0_read <= crystals_2_0_read;
        ap_port_reg_crystals_2_1_read <= crystals_2_1_read;
        ap_port_reg_crystals_2_2_read <= crystals_2_2_read;
        ap_port_reg_crystals_2_3_read <= crystals_2_3_read;
        ap_port_reg_crystals_2_4_read <= crystals_2_4_read;
        ap_port_reg_crystals_3_0_read <= crystals_3_0_read;
        ap_port_reg_crystals_3_1_read <= crystals_3_1_read;
        ap_port_reg_crystals_3_2_read <= crystals_3_2_read;
        ap_port_reg_crystals_3_3_read <= crystals_3_3_read;
        ap_port_reg_crystals_3_4_read <= crystals_3_4_read;
        ap_port_reg_crystals_4_2_read <= crystals_4_2_read;
        ap_port_reg_crystals_4_3_read <= crystals_4_3_read;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
        clusterET_1_reg_851 <= clusterET_1_fu_541_p3;
        etaStripSum_0_reg_789 <= etaStripSum_0_fu_443_p2;
        etaStripSum_2_reg_796 <= etaStripSum_2_fu_459_p2;
        etaStripSum_3_reg_804 <= etaStripSum_3_fu_475_p2;
        newSel2_reg_871 <= newSel2_fu_614_p3;
        phiStripSum_2_reg_777 <= phiStripSum_2_fu_410_p2;
        phiStripSum_3_reg_783 <= phiStripSum_3_fu_427_p2;
        tmp35_reg_812 <= tmp35_fu_481_p2;
        tmp_48_1_reg_856 <= tmp_48_1_fu_549_p2;
        tmp_48_2_reg_866 <= tmp_48_2_fu_575_p2;
        tmp_50_1_reg_861 <= tmp_50_1_fu_564_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_pp0_stage0 == 1'b1) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)))) begin
        crystals_1_0_read_1_reg_673 <= crystals_1_0_read;
        crystals_4_0_read_1_reg_668 <= crystals_4_0_read;
        tmp17_reg_688 <= tmp17_fu_268_p2;
        tmp23_reg_693 <= tmp23_fu_274_p2;
        tmp32_reg_698 <= tmp32_fu_280_p2;
        tmp5_reg_678 <= tmp5_fu_256_p2;
        tmp8_reg_683 <= tmp8_fu_262_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
        tmp_42_4_reg_817 <= tmp_42_4_fu_493_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((ap_CS_fsm_pp0_stage0 == 1'b1)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_pp0_stage0 == 1'b1) & (1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter0))) begin
        ap_pipeline_idle_pp0 = 1'b1;
    end else begin
        ap_pipeline_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_start == 1'b0)) & ~((1'b0 == ap_start) & (1'b0 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage2;
        end
        ap_ST_fsm_pp0_stage2 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage3;
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (~(1'b1 == ap_pipeline_idle_pp0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage5;
        end
        ap_ST_fsm_pp0_stage5 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[ap_const_lv32_5];

assign ap_return_0 = mrv_trunc_ext_fu_639_p1;

assign ap_return_1 = mrv_1_trunc_ext_fu_648_p1;

assign ap_return_2 = tmp_42_4_reg_817;

assign ap_return_3 = clusterET_1_2_fu_632_p3;

assign clusterET_1_1_fu_622_p3 = ((tmp_48_1_reg_856[0:0] === 1'b1) ? tmp_50_1_reg_861 : clusterET_1_reg_851);

assign clusterET_1_2_fu_632_p3 = ((tmp_48_2_reg_866[0:0] === 1'b1) ? tmp_50_2_fu_627_p2 : clusterET_1_1_fu_622_p3);

assign clusterET_1_fu_541_p3 = ((or_cond_4_fu_519_p2[0:0] === 1'b1) ? tmp_19_fu_530_p7 : ap_const_lv16_0);

assign etaStripSum_0_fu_443_p2 = (tmp19_fu_433_p2 + tmp21_fu_439_p2);

assign etaStripSum_1_fu_365_p2 = (tmp22_fu_355_p2 + tmp24_fu_361_p2);

assign etaStripSum_2_fu_459_p2 = (tmp25_fu_449_p2 + tmp27_fu_455_p2);

assign etaStripSum_3_fu_475_p2 = (tmp28_fu_465_p2 + tmp30_fu_471_p2);

assign etaStripSum_4_fu_393_p2 = (tmp31_fu_383_p2 + tmp33_fu_389_p2);

assign eta_3_2_fu_570_p2 = (tmp_46_cast_cast_reg_841 + ap_const_lv4_1);

assign eta_3_fu_503_p2 = ($signed(tmp_46_cast_cast_fu_499_p1) + $signed(ap_const_lv4_F));

assign grp_getPeakBinOf5_fu_236_ap_start = ap_reg_grp_getPeakBinOf5_fu_236_ap_start;

assign grp_getPeakBinOf5_fu_246_ap_start = ap_reg_grp_getPeakBinOf5_fu_246_ap_start;

assign mrv_1_trunc_ext_fu_648_p1 = peakPhi_write_assign_reg_836;

assign mrv_trunc_ext_fu_639_p1 = tmp_s_reg_824;

assign newSel1_fu_608_p3 = ((sel_tmp_fu_581_p2[0:0] === 1'b1) ? etaStripSum_2_reg_796 : ap_pipeline_reg_pp0_iter1_etaStripSum_4_reg_769);

assign newSel2_fu_614_p3 = ((or_cond_fu_602_p2[0:0] === 1'b1) ? newSel_fu_596_p3 : newSel1_fu_608_p3);

assign newSel_fu_596_p3 = ((sel_tmp4_fu_591_p2[0:0] === 1'b1) ? ap_pipeline_reg_pp0_iter1_etaStripSum_1_reg_751 : etaStripSum_3_reg_804);

assign or_cond_4_fu_519_p2 = (tmp_17_fu_509_p2 & tmp_18_fu_514_p2);

assign or_cond_fu_602_p2 = (sel_tmp4_fu_591_p2 | sel_tmp2_fu_586_p2);

assign phiStripSum_0_fu_297_p2 = (tmp_fu_286_p2 + tmp6_fu_292_p2);

assign phiStripSum_1_fu_314_p2 = (tmp7_fu_303_p2 + tmp9_fu_309_p2);

assign phiStripSum_2_fu_410_p2 = (tmp10_fu_399_p2 + tmp12_fu_405_p2);

assign phiStripSum_3_fu_427_p2 = (tmp13_fu_416_p2 + tmp15_fu_422_p2);

assign phiStripSum_4_fu_343_p2 = (tmp16_fu_332_p2 + tmp18_fu_338_p2);

assign sel_tmp2_fu_586_p2 = ((tmp_s_reg_824 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_591_p2 = ((tmp_s_reg_824 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign sel_tmp_fu_581_p2 = ((tmp_s_reg_824 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign tmp10_fu_399_p2 = (ap_port_reg_crystals_3_2_read + ap_port_reg_crystals_2_2_read);

assign tmp11_fu_320_p2 = (ap_port_reg_crystals_4_2_read + ap_port_reg_crystals_1_2_read);

assign tmp12_fu_405_p2 = (ap_port_reg_crystals_0_2_read + tmp11_reg_730);

assign tmp13_fu_416_p2 = (ap_port_reg_crystals_3_3_read + ap_port_reg_crystals_2_3_read);

assign tmp14_fu_326_p2 = (ap_port_reg_crystals_4_3_read + ap_port_reg_crystals_1_3_read);

assign tmp15_fu_422_p2 = (ap_port_reg_crystals_0_3_read + tmp14_reg_735);

assign tmp16_fu_332_p2 = (ap_port_reg_crystals_3_4_read + ap_port_reg_crystals_2_4_read);

assign tmp17_fu_268_p2 = (crystals_4_4_read + crystals_1_4_read);

assign tmp18_fu_338_p2 = (ap_port_reg_crystals_0_4_read + tmp17_reg_688);

assign tmp19_fu_433_p2 = (ap_port_reg_crystals_0_3_read + ap_port_reg_crystals_0_2_read);

assign tmp20_fu_349_p2 = (ap_port_reg_crystals_0_4_read + ap_port_reg_crystals_0_1_read);

assign tmp21_fu_439_p2 = (crystals_0_0_read_1_reg_713 + tmp20_reg_746);

assign tmp22_fu_355_p2 = (ap_port_reg_crystals_1_3_read + ap_port_reg_crystals_1_2_read);

assign tmp23_fu_274_p2 = (crystals_1_4_read + crystals_1_1_read);

assign tmp24_fu_361_p2 = (crystals_1_0_read_1_reg_673 + tmp23_reg_693);

assign tmp25_fu_449_p2 = (ap_port_reg_crystals_2_3_read + ap_port_reg_crystals_2_2_read);

assign tmp26_fu_371_p2 = (ap_port_reg_crystals_2_4_read + ap_port_reg_crystals_2_1_read);

assign tmp27_fu_455_p2 = (crystals_2_0_read_1_reg_708 + tmp26_reg_759);

assign tmp28_fu_465_p2 = (ap_port_reg_crystals_3_3_read + ap_port_reg_crystals_3_2_read);

assign tmp29_fu_377_p2 = (ap_port_reg_crystals_3_4_read + ap_port_reg_crystals_3_1_read);

assign tmp30_fu_471_p2 = (crystals_3_0_read_1_reg_703 + tmp29_reg_764);

assign tmp31_fu_383_p2 = (ap_port_reg_crystals_4_3_read + ap_port_reg_crystals_4_2_read);

assign tmp32_fu_280_p2 = (crystals_4_4_read + crystals_4_1_read);

assign tmp33_fu_389_p2 = (crystals_4_0_read_1_reg_668 + tmp32_reg_698);

assign tmp34_fu_485_p2 = (phiStripSum_3_reg_783 + phiStripSum_2_reg_777);

assign tmp35_fu_481_p2 = (phiStripSum_4_reg_740 + phiStripSum_0_reg_718);

assign tmp36_fu_489_p2 = (phiStripSum_1_reg_724 + tmp35_reg_812);

assign tmp5_fu_256_p2 = (crystals_4_0_read + crystals_1_0_read);

assign tmp6_fu_292_p2 = (ap_port_reg_crystals_0_0_read + tmp5_reg_678);

assign tmp7_fu_303_p2 = (ap_port_reg_crystals_3_1_read + ap_port_reg_crystals_2_1_read);

assign tmp8_fu_262_p2 = (crystals_4_1_read + crystals_1_1_read);

assign tmp9_fu_309_p2 = (ap_port_reg_crystals_0_1_read + tmp8_reg_683);

assign tmp_17_fu_509_p2 = ((tmp_s_reg_824 != ap_const_lv3_0) ? 1'b1 : 1'b0);

assign tmp_18_fu_514_p2 = (($signed(eta_3_reg_846) < $signed(4'b101)) ? 1'b1 : 1'b0);

assign tmp_19_fu_530_p6 = ($signed(tmp_s_reg_824) + $signed(ap_const_lv3_7));

assign tmp_42_4_fu_493_p2 = (tmp34_fu_485_p2 + tmp36_fu_489_p2);

assign tmp_46_cast_cast_fu_499_p1 = grp_getPeakBinOf5_fu_236_ap_return;

assign tmp_48_1_fu_549_p2 = ((tmp_s_reg_824 < ap_const_lv3_5) ? 1'b1 : 1'b0);

assign tmp_48_2_fu_575_p2 = ((eta_3_2_fu_570_p2 < ap_const_lv4_5) ? 1'b1 : 1'b0);

assign tmp_50_1_fu_564_p2 = (tmp_20_fu_554_p7 + clusterET_1_fu_541_p3);

assign tmp_50_2_fu_627_p2 = (newSel2_reg_871 + clusterET_1_1_fu_622_p3);

assign tmp_fu_286_p2 = (ap_port_reg_crystals_3_0_read + ap_port_reg_crystals_2_0_read);

always @ (posedge ap_clk) begin
    tmp_46_cast_cast_reg_841[3] <= 1'b0;
end

endmodule //getClustersInTower
