-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bitonic8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ClusterDeposits_0_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_1_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_2_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_3_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_4_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_5_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_6_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_7_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_8_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_9_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_60 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_61 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_62 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_63 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_64 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_65 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_66 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_67 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_68 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_69 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_70 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_71 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_72 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_73 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_74 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_75 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_76 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_77 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_78 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_79 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_80 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_81 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_82 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_83 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_84 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_85 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_86 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_87 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_88 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_89 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of bitonic8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal tmp_s_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1108 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read4_read_fu_296_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read4_read_reg_1116 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_read4_fu_304_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_read4_reg_1122 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_194_1_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_1_reg_1128 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read5_read1_fu_318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read5_read1_reg_1136 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_read5_fu_326_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_read5_reg_1142 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_194_2_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_2_reg_1148 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read6_read2_fu_340_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read6_read2_reg_1156 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_read6_fu_348_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_read6_reg_1162 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_194_3_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_3_reg_1168 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read7_read3_fu_362_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read7_read3_reg_1176 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read3_read7_fu_370_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read3_read7_reg_1182 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_37_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_reg_1188 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_reg_1198 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_211_1_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_211_1_reg_1208 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_216_1_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_216_1_reg_1218 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read40_s_fu_520_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read40_s_reg_1228 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal p_read72_s_fu_540_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read72_s_reg_1233 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read41_s_fu_566_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read41_s_reg_1238 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read73_s_fu_586_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read73_s_reg_1243 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta45_0_Clust_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta45_0_Clust_reg_1248 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterPhi76_0_Clust_fu_784_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterPhi76_0_Clust_reg_1253 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read43_ClusterEta_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read43_ClusterEta_reg_1258 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read75_ClusterPhi_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read75_ClusterPhi_reg_1263 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_SEBB4_fu_844_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_SEBB4_reg_1268 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_SEBB5_fu_852_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_SEBB5_reg_1273 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_0_Clust_1_fu_860_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_0_Clust_1_reg_1278 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_1_Cluster_fu_868_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_1_Cluster_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_0_Clust_1_fu_876_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_0_Clust_1_reg_1288 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_1_Cluster_fu_884_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_1_Cluster_reg_1293 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_1_C_fu_898_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_1_C_reg_1298 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_1_C_fu_906_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_1_C_reg_1303 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_1_Clust_fu_914_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_1_Clust_reg_1308 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta33_1_Clust_fu_922_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta33_1_Clust_reg_1313 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_1_Clust_fu_930_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_1_Clust_reg_1318 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi64_1_Clust_fu_938_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi64_1_Clust_reg_1323 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_1_C_fu_952_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_1_C_reg_1328 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_1_C_fu_960_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_1_C_reg_1333 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta36_1_Clust_fu_968_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta36_1_Clust_reg_1338 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_1_Clust_fu_976_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_1_Clust_reg_1343 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_1_Clust_fu_984_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_1_Clust_reg_1348 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_1_Clust_fu_992_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_1_Clust_reg_1353 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_1_C_fu_1006_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_1_C_reg_1358 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_1_C_fu_1014_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_1_C_reg_1363 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta38_1_Clust_fu_1022_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta38_1_Clust_reg_1368 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_1_Clu_fu_1030_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_1_Clu_reg_1373 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_1_Clust_fu_1038_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_1_Clust_reg_1378 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_1_Clust_fu_1046_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_1_Clust_reg_1383 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits1316_s_fu_1060_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits1316_s_reg_1388 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits14_1_s_fu_1068_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits14_1_s_reg_1393 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta44_0_rea_1_fu_1076_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta44_0_rea_1_reg_1398 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta45_1_Clust_fu_1084_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta45_1_Clust_reg_1403 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi75_0_rea_1_fu_1092_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi75_0_rea_1_reg_1408 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi76_1_Clust_fu_1100_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi76_1_Clust_reg_1413 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_preg : STD_LOGIC := '0';
    signal ap_port_reg_ClusterDeposits_8_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_9_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_0_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_1_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_2_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_3_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_4_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_5_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_6_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_7_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_8_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_9_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_0_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_1_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_2_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_3_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_4_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_5_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_6_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_7_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_8_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_9_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_start : STD_LOGIC;
    signal grp_bitonic16_fu_248_ap_done : STD_LOGIC;
    signal grp_bitonic16_fu_248_ap_idle : STD_LOGIC;
    signal grp_bitonic16_fu_248_ap_ready : STD_LOGIC;
    signal grp_bitonic16_fu_248_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_20 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_21 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_22 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_30 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_31 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_32 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_33 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_34 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_35 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_36 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_37 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_38 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_39 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_40 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_41 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_42 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_43 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_44 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_45 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_46 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_47 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_48 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_49 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_50 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_51 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_52 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_53 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_54 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_55 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_56 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_57 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_58 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_59 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_60 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_61 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_62 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_63 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_64 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_65 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_66 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_67 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_68 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_69 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_70 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_71 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_72 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_73 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_74 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_75 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_76 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_77 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_78 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_79 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_80 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_81 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_82 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_83 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_84 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_85 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_86 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_87 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_88 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bitonic16_fu_248_ap_return_89 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_grp_bitonic16_fu_248_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal tmp_36_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read_fu_528_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read8_fu_548_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_198_1_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read9_fu_574_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_fu_594_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read38_read_fu_458_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read36_read_fu_402_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read70_read_fu_472_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read68_read_fu_416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read39_read_fu_486_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read37_read_fu_430_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read71_read_fu_500_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read69_read_fu_444_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read34_read_fu_465_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read32_read_fu_409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read66_read_fu_479_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read64_read_fu_423_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read35_read_fu_493_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read33_read_fu_437_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read67_read_fu_507_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read65_read_fu_451_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_221_1_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_536_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_221_1_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_65_fu_556_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_226_1_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_66_fu_582_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_226_1_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_67_fu_602_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read6_read2_read4_fu_606_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_0_C_fu_644_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_39_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta34_0_Clust_fu_654_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read38_read34_rea_fu_616_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_0_Clust_fu_668_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read70_read66_rea_fu_630_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read4_read_read6_s_fu_611_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits12_0_s_fu_649_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_251_1_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta32_0_Clust_fu_661_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read36_read32_rea_fu_623_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi63_0_Clust_fu_675_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read68_read64_rea_fu_637_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_0_C_fu_682_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_0_C_fu_720_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_251_2_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta38_0_Clust_fu_730_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_0_Clu_fu_692_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_0_Clust_fu_744_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_0_Clust_fu_706_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_0_C_fu_687_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_0_C_fu_725_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_251_3_fu_1000_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta36_0_Clust_fu_737_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_0_Clust_fu_699_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_0_Clust_fu_751_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_0_Clust_fu_713_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_256_3_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta44_0_rea_fu_816_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta43_0_Clust_fu_776_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi75_0_rea_fu_830_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi74_0_Clust_fu_790_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;

    component bitonic16 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ClusterDeposits_0_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_1_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_2_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_3_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_4_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_5_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_6_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_7_r : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_14_s : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterDeposits_15_s : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_12_read : IN STD_LOGIC_VECTOR (0 downto 0);
        ClusterEta_13_read : IN STD_LOGIC_VECTOR (0 downto 0);
        ClusterEta_14_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterEta_15_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_12_read : IN STD_LOGIC_VECTOR (0 downto 0);
        ClusterPhi_13_read : IN STD_LOGIC_VECTOR (0 downto 0);
        ClusterPhi_14_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ClusterPhi_15_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_32 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_33 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_34 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_35 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_36 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_37 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_38 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_39 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_40 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_41 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_42 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_43 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_44 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_45 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_46 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_47 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_48 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_49 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_50 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_51 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_52 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_53 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_54 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_55 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_56 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_57 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_58 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_59 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_60 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_61 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_62 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_63 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_64 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_65 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_66 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_67 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_68 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_69 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_70 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_71 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_72 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_73 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_74 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_75 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_76 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_77 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_78 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_79 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_80 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_81 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_82 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_83 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_84 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_85 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_86 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_87 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_88 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_89 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_bitonic16_fu_248 : component bitonic16
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bitonic16_fu_248_ap_start,
        ap_done => grp_bitonic16_fu_248_ap_done,
        ap_idle => grp_bitonic16_fu_248_ap_idle,
        ap_ready => grp_bitonic16_fu_248_ap_ready,
        ClusterDeposits_0_r => sel_SEBB4_reg_1268,
        ClusterDeposits_1_r => sel_SEBB5_reg_1273,
        ClusterDeposits_2_r => ClusterDeposits3_1_C_reg_1298,
        ClusterDeposits_3_r => ClusterDeposits2_1_C_reg_1303,
        ClusterDeposits_4_r => ClusterDeposits5_1_C_reg_1328,
        ClusterDeposits_5_r => ClusterDeposits4_1_C_reg_1333,
        ClusterDeposits_6_r => ClusterDeposits7_1_C_reg_1358,
        ClusterDeposits_7_r => ClusterDeposits6_1_C_reg_1363,
        ClusterDeposits_14_s => ClusterDeposits1316_s_reg_1388,
        ClusterDeposits_15_s => ClusterDeposits14_1_s_reg_1393,
        ClusterEta_0_read => ClusterEta34_0_Clust_1_reg_1278,
        ClusterEta_1_read => ClusterEta_1_Cluster_reg_1283,
        ClusterEta_2_read => ClusterEta34_1_Clust_reg_1308,
        ClusterEta_3_read => ClusterEta33_1_Clust_reg_1313,
        ClusterEta_4_read => ClusterEta36_1_Clust_reg_1338,
        ClusterEta_5_read => ClusterEta35_1_Clust_reg_1343,
        ClusterEta_6_read => ClusterEta38_1_Clust_reg_1368,
        ClusterEta_7_read => ClusterEta3743_1_Clu_reg_1373,
        ClusterEta_8_read => p_read40_s_reg_1228,
        ClusterEta_9_read => p_read41_s_reg_1238,
        ClusterEta_12_read => ClusterEta45_0_Clust_reg_1248,
        ClusterEta_13_read => p_read43_ClusterEta_reg_1258,
        ClusterEta_14_read => ClusterEta44_0_rea_1_reg_1398,
        ClusterEta_15_read => ClusterEta45_1_Clust_reg_1403,
        ClusterPhi_0_read => ClusterPhi65_0_Clust_1_reg_1288,
        ClusterPhi_1_read => ClusterPhi_1_Cluster_reg_1293,
        ClusterPhi_2_read => ClusterPhi65_1_Clust_reg_1318,
        ClusterPhi_3_read => ClusterPhi64_1_Clust_reg_1323,
        ClusterPhi_4_read => ClusterPhi67_1_Clust_reg_1348,
        ClusterPhi_5_read => ClusterPhi66_1_Clust_reg_1353,
        ClusterPhi_6_read => ClusterPhi69_1_Clust_reg_1378,
        ClusterPhi_7_read => ClusterPhi68_1_Clust_reg_1383,
        ClusterPhi_8_read => p_read72_s_reg_1233,
        ClusterPhi_9_read => p_read73_s_reg_1243,
        ClusterPhi_12_read => ClusterPhi76_0_Clust_reg_1253,
        ClusterPhi_13_read => p_read75_ClusterPhi_reg_1263,
        ClusterPhi_14_read => ClusterPhi75_0_rea_1_reg_1408,
        ClusterPhi_15_read => ClusterPhi76_1_Clust_reg_1413,
        ap_return_0 => grp_bitonic16_fu_248_ap_return_0,
        ap_return_1 => grp_bitonic16_fu_248_ap_return_1,
        ap_return_2 => grp_bitonic16_fu_248_ap_return_2,
        ap_return_3 => grp_bitonic16_fu_248_ap_return_3,
        ap_return_4 => grp_bitonic16_fu_248_ap_return_4,
        ap_return_5 => grp_bitonic16_fu_248_ap_return_5,
        ap_return_6 => grp_bitonic16_fu_248_ap_return_6,
        ap_return_7 => grp_bitonic16_fu_248_ap_return_7,
        ap_return_8 => grp_bitonic16_fu_248_ap_return_8,
        ap_return_9 => grp_bitonic16_fu_248_ap_return_9,
        ap_return_10 => grp_bitonic16_fu_248_ap_return_10,
        ap_return_11 => grp_bitonic16_fu_248_ap_return_11,
        ap_return_12 => grp_bitonic16_fu_248_ap_return_12,
        ap_return_13 => grp_bitonic16_fu_248_ap_return_13,
        ap_return_14 => grp_bitonic16_fu_248_ap_return_14,
        ap_return_15 => grp_bitonic16_fu_248_ap_return_15,
        ap_return_16 => grp_bitonic16_fu_248_ap_return_16,
        ap_return_17 => grp_bitonic16_fu_248_ap_return_17,
        ap_return_18 => grp_bitonic16_fu_248_ap_return_18,
        ap_return_19 => grp_bitonic16_fu_248_ap_return_19,
        ap_return_20 => grp_bitonic16_fu_248_ap_return_20,
        ap_return_21 => grp_bitonic16_fu_248_ap_return_21,
        ap_return_22 => grp_bitonic16_fu_248_ap_return_22,
        ap_return_23 => grp_bitonic16_fu_248_ap_return_23,
        ap_return_24 => grp_bitonic16_fu_248_ap_return_24,
        ap_return_25 => grp_bitonic16_fu_248_ap_return_25,
        ap_return_26 => grp_bitonic16_fu_248_ap_return_26,
        ap_return_27 => grp_bitonic16_fu_248_ap_return_27,
        ap_return_28 => grp_bitonic16_fu_248_ap_return_28,
        ap_return_29 => grp_bitonic16_fu_248_ap_return_29,
        ap_return_30 => grp_bitonic16_fu_248_ap_return_30,
        ap_return_31 => grp_bitonic16_fu_248_ap_return_31,
        ap_return_32 => grp_bitonic16_fu_248_ap_return_32,
        ap_return_33 => grp_bitonic16_fu_248_ap_return_33,
        ap_return_34 => grp_bitonic16_fu_248_ap_return_34,
        ap_return_35 => grp_bitonic16_fu_248_ap_return_35,
        ap_return_36 => grp_bitonic16_fu_248_ap_return_36,
        ap_return_37 => grp_bitonic16_fu_248_ap_return_37,
        ap_return_38 => grp_bitonic16_fu_248_ap_return_38,
        ap_return_39 => grp_bitonic16_fu_248_ap_return_39,
        ap_return_40 => grp_bitonic16_fu_248_ap_return_40,
        ap_return_41 => grp_bitonic16_fu_248_ap_return_41,
        ap_return_42 => grp_bitonic16_fu_248_ap_return_42,
        ap_return_43 => grp_bitonic16_fu_248_ap_return_43,
        ap_return_44 => grp_bitonic16_fu_248_ap_return_44,
        ap_return_45 => grp_bitonic16_fu_248_ap_return_45,
        ap_return_46 => grp_bitonic16_fu_248_ap_return_46,
        ap_return_47 => grp_bitonic16_fu_248_ap_return_47,
        ap_return_48 => grp_bitonic16_fu_248_ap_return_48,
        ap_return_49 => grp_bitonic16_fu_248_ap_return_49,
        ap_return_50 => grp_bitonic16_fu_248_ap_return_50,
        ap_return_51 => grp_bitonic16_fu_248_ap_return_51,
        ap_return_52 => grp_bitonic16_fu_248_ap_return_52,
        ap_return_53 => grp_bitonic16_fu_248_ap_return_53,
        ap_return_54 => grp_bitonic16_fu_248_ap_return_54,
        ap_return_55 => grp_bitonic16_fu_248_ap_return_55,
        ap_return_56 => grp_bitonic16_fu_248_ap_return_56,
        ap_return_57 => grp_bitonic16_fu_248_ap_return_57,
        ap_return_58 => grp_bitonic16_fu_248_ap_return_58,
        ap_return_59 => grp_bitonic16_fu_248_ap_return_59,
        ap_return_60 => grp_bitonic16_fu_248_ap_return_60,
        ap_return_61 => grp_bitonic16_fu_248_ap_return_61,
        ap_return_62 => grp_bitonic16_fu_248_ap_return_62,
        ap_return_63 => grp_bitonic16_fu_248_ap_return_63,
        ap_return_64 => grp_bitonic16_fu_248_ap_return_64,
        ap_return_65 => grp_bitonic16_fu_248_ap_return_65,
        ap_return_66 => grp_bitonic16_fu_248_ap_return_66,
        ap_return_67 => grp_bitonic16_fu_248_ap_return_67,
        ap_return_68 => grp_bitonic16_fu_248_ap_return_68,
        ap_return_69 => grp_bitonic16_fu_248_ap_return_69,
        ap_return_70 => grp_bitonic16_fu_248_ap_return_70,
        ap_return_71 => grp_bitonic16_fu_248_ap_return_71,
        ap_return_72 => grp_bitonic16_fu_248_ap_return_72,
        ap_return_73 => grp_bitonic16_fu_248_ap_return_73,
        ap_return_74 => grp_bitonic16_fu_248_ap_return_74,
        ap_return_75 => grp_bitonic16_fu_248_ap_return_75,
        ap_return_76 => grp_bitonic16_fu_248_ap_return_76,
        ap_return_77 => grp_bitonic16_fu_248_ap_return_77,
        ap_return_78 => grp_bitonic16_fu_248_ap_return_78,
        ap_return_79 => grp_bitonic16_fu_248_ap_return_79,
        ap_return_80 => grp_bitonic16_fu_248_ap_return_80,
        ap_return_81 => grp_bitonic16_fu_248_ap_return_81,
        ap_return_82 => grp_bitonic16_fu_248_ap_return_82,
        ap_return_83 => grp_bitonic16_fu_248_ap_return_83,
        ap_return_84 => grp_bitonic16_fu_248_ap_return_84,
        ap_return_85 => grp_bitonic16_fu_248_ap_return_85,
        ap_return_86 => grp_bitonic16_fu_248_ap_return_86,
        ap_return_87 => grp_bitonic16_fu_248_ap_return_87,
        ap_return_88 => grp_bitonic16_fu_248_ap_return_88,
        ap_return_89 => grp_bitonic16_fu_248_ap_return_89);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_preg <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter0_preg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage5)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_bitonic16_fu_248_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bitonic16_fu_248_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_reg_grp_bitonic16_fu_248_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bitonic16_fu_248_ap_ready)) then 
                    ap_reg_grp_bitonic16_fu_248_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then
                ClusterDeposits1316_s_reg_1388 <= ClusterDeposits1316_s_fu_1060_p3;
                ClusterDeposits14_1_s_reg_1393 <= ClusterDeposits14_1_s_fu_1068_p3;
                ClusterDeposits2_1_C_reg_1303 <= ClusterDeposits2_1_C_fu_906_p3;
                ClusterDeposits3_1_C_reg_1298 <= ClusterDeposits3_1_C_fu_898_p3;
                ClusterDeposits4_1_C_reg_1333 <= ClusterDeposits4_1_C_fu_960_p3;
                ClusterDeposits5_1_C_reg_1328 <= ClusterDeposits5_1_C_fu_952_p3;
                ClusterDeposits6_1_C_reg_1363 <= ClusterDeposits6_1_C_fu_1014_p3;
                ClusterDeposits7_1_C_reg_1358 <= ClusterDeposits7_1_C_fu_1006_p3;
                ClusterEta33_1_Clust_reg_1313 <= ClusterEta33_1_Clust_fu_922_p3;
                ClusterEta34_0_Clust_1_reg_1278 <= ClusterEta34_0_Clust_1_fu_860_p3;
                ClusterEta34_1_Clust_reg_1308 <= ClusterEta34_1_Clust_fu_914_p3;
                ClusterEta35_1_Clust_reg_1343 <= ClusterEta35_1_Clust_fu_976_p3;
                ClusterEta36_1_Clust_reg_1338 <= ClusterEta36_1_Clust_fu_968_p3;
                ClusterEta3743_1_Clu_reg_1373 <= ClusterEta3743_1_Clu_fu_1030_p3;
                ClusterEta38_1_Clust_reg_1368 <= ClusterEta38_1_Clust_fu_1022_p3;
                ClusterEta44_0_rea_1_reg_1398 <= ClusterEta44_0_rea_1_fu_1076_p3;
                ClusterEta45_0_Clust_reg_1248 <= ClusterEta45_0_Clust_fu_770_p2;
                ClusterEta45_1_Clust_reg_1403 <= ClusterEta45_1_Clust_fu_1084_p3;
                ClusterEta_1_Cluster_reg_1283 <= ClusterEta_1_Cluster_fu_868_p3;
                ClusterPhi64_1_Clust_reg_1323 <= ClusterPhi64_1_Clust_fu_938_p3;
                ClusterPhi65_0_Clust_1_reg_1288 <= ClusterPhi65_0_Clust_1_fu_876_p3;
                ClusterPhi65_1_Clust_reg_1318 <= ClusterPhi65_1_Clust_fu_930_p3;
                ClusterPhi66_1_Clust_reg_1353 <= ClusterPhi66_1_Clust_fu_992_p3;
                ClusterPhi67_1_Clust_reg_1348 <= ClusterPhi67_1_Clust_fu_984_p3;
                ClusterPhi68_1_Clust_reg_1383 <= ClusterPhi68_1_Clust_fu_1046_p3;
                ClusterPhi69_1_Clust_reg_1378 <= ClusterPhi69_1_Clust_fu_1038_p3;
                ClusterPhi75_0_rea_1_reg_1408 <= ClusterPhi75_0_rea_1_fu_1092_p3;
                ClusterPhi76_0_Clust_reg_1253 <= ClusterPhi76_0_Clust_fu_784_p2;
                ClusterPhi76_1_Clust_reg_1413 <= ClusterPhi76_1_Clust_fu_1100_p3;
                ClusterPhi_1_Cluster_reg_1293 <= ClusterPhi_1_Cluster_fu_884_p3;
                p_read40_s_reg_1228 <= p_read40_s_fu_520_p3;
                p_read41_s_reg_1238 <= p_read41_s_fu_566_p3;
                p_read43_ClusterEta_reg_1258 <= p_read43_ClusterEta_fu_810_p2;
                p_read72_s_reg_1233 <= p_read72_s_fu_540_p3;
                p_read73_s_reg_1243 <= p_read73_s_fu_586_p3;
                p_read75_ClusterPhi_reg_1263 <= p_read75_ClusterPhi_fu_824_p2;
                sel_SEBB4_reg_1268 <= sel_SEBB4_fu_844_p3;
                sel_SEBB5_reg_1273 <= sel_SEBB5_fu_852_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_port_reg_ClusterDeposits_8_r <= ClusterDeposits_8_r;
                ap_port_reg_ClusterDeposits_9_r <= ClusterDeposits_9_r;
                ap_port_reg_ClusterEta_0_read <= ClusterEta_0_read;
                ap_port_reg_ClusterEta_1_read <= ClusterEta_1_read;
                ap_port_reg_ClusterEta_2_read <= ClusterEta_2_read;
                ap_port_reg_ClusterEta_3_read <= ClusterEta_3_read;
                ap_port_reg_ClusterEta_4_read <= ClusterEta_4_read;
                ap_port_reg_ClusterEta_5_read <= ClusterEta_5_read;
                ap_port_reg_ClusterEta_6_read <= ClusterEta_6_read;
                ap_port_reg_ClusterEta_7_read <= ClusterEta_7_read;
                ap_port_reg_ClusterEta_8_read <= ClusterEta_8_read;
                ap_port_reg_ClusterEta_9_read <= ClusterEta_9_read;
                ap_port_reg_ClusterPhi_0_read <= ClusterPhi_0_read;
                ap_port_reg_ClusterPhi_1_read <= ClusterPhi_1_read;
                ap_port_reg_ClusterPhi_2_read <= ClusterPhi_2_read;
                ap_port_reg_ClusterPhi_3_read <= ClusterPhi_3_read;
                ap_port_reg_ClusterPhi_4_read <= ClusterPhi_4_read;
                ap_port_reg_ClusterPhi_5_read <= ClusterPhi_5_read;
                ap_port_reg_ClusterPhi_6_read <= ClusterPhi_6_read;
                ap_port_reg_ClusterPhi_7_read <= ClusterPhi_7_read;
                ap_port_reg_ClusterPhi_8_read <= ClusterPhi_8_read;
                ap_port_reg_ClusterPhi_9_read <= ClusterPhi_9_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                p_read1_read5_reg_1142 <= p_read1_read5_fu_326_p3;
                p_read2_read6_reg_1162 <= p_read2_read6_fu_348_p3;
                p_read3_read7_reg_1182 <= p_read3_read7_fu_370_p3;
                p_read4_read_reg_1116 <= p_read4_read_fu_296_p3;
                p_read5_read1_reg_1136 <= p_read5_read1_fu_318_p3;
                p_read6_read2_reg_1156 <= p_read6_read2_fu_340_p3;
                p_read7_read3_reg_1176 <= p_read7_read3_fu_362_p3;
                p_read_read4_reg_1122 <= p_read_read4_fu_304_p3;
                tmp_194_1_reg_1128 <= tmp_194_1_fu_312_p2;
                tmp_194_2_reg_1148 <= tmp_194_2_fu_334_p2;
                tmp_194_3_reg_1168 <= tmp_194_3_fu_356_p2;
                tmp_211_1_reg_1208 <= tmp_211_1_fu_390_p2;
                tmp_216_1_reg_1218 <= tmp_216_1_fu_396_p2;
                tmp_37_reg_1188 <= tmp_37_fu_378_p2;
                tmp_38_reg_1198 <= tmp_38_fu_384_p2;
                tmp_s_reg_1108 <= tmp_s_fu_290_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not(((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if (not((ap_const_logic_1 = ap_pipeline_idle_pp0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
            when ap_ST_fsm_pp0_stage3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
            when ap_ST_fsm_pp0_stage4 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
            when ap_ST_fsm_pp0_stage5 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ClusterDeposits12_0_s_fu_649_p3 <= 
        p_read5_read1_reg_1136 when (tmp_38_reg_1198(0) = '1') else 
        p_read7_read3_reg_1176;
    ClusterDeposits1316_s_fu_1060_p3 <= 
        ap_port_reg_ClusterDeposits_9_r when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_8_r;
    ClusterDeposits14_1_s_fu_1068_p3 <= 
        ap_port_reg_ClusterDeposits_8_r when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_9_r;
    ClusterDeposits2_1_C_fu_906_p3 <= 
        p_read4_read_read6_s_fu_611_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        ClusterDeposits12_0_s_fu_649_p3;
    ClusterDeposits3_0_C_fu_644_p3 <= 
        p_read7_read3_reg_1176 when (tmp_38_reg_1198(0) = '1') else 
        p_read5_read1_reg_1136;
    ClusterDeposits3_1_C_fu_898_p3 <= 
        ClusterDeposits12_0_s_fu_649_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        p_read4_read_read6_s_fu_611_p3;
    ClusterDeposits4_0_C_fu_687_p3 <= 
        p_read_read4_reg_1122 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read2_read6_reg_1162;
    ClusterDeposits4_1_C_fu_960_p3 <= 
        ClusterDeposits6_0_C_fu_682_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterDeposits7_0_C_fu_720_p3;
    ClusterDeposits5_0_C_fu_725_p3 <= 
        p_read1_read5_reg_1142 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read3_read7_reg_1182;
    ClusterDeposits5_1_C_fu_952_p3 <= 
        ClusterDeposits7_0_C_fu_720_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterDeposits6_0_C_fu_682_p3;
    ClusterDeposits6_0_C_fu_682_p3 <= 
        p_read2_read6_reg_1162 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read_read4_reg_1122;
    ClusterDeposits6_1_C_fu_1014_p3 <= 
        ClusterDeposits4_0_C_fu_687_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterDeposits5_0_C_fu_725_p3;
    ClusterDeposits7_0_C_fu_720_p3 <= 
        p_read3_read7_reg_1182 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read1_read5_reg_1142;
    ClusterDeposits7_1_C_fu_1006_p3 <= 
        ClusterDeposits5_0_C_fu_725_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterDeposits4_0_C_fu_687_p3;
    ClusterEta32_0_Clust_fu_661_p3 <= 
        p_read37_read_fu_430_p3 when (tmp_38_reg_1198(0) = '1') else 
        p_read39_read_fu_486_p3;
    ClusterEta33_1_Clust_fu_922_p3 <= 
        p_read36_read32_rea_fu_623_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        ClusterEta32_0_Clust_fu_661_p3;
    ClusterEta34_0_Clust_1_fu_860_p3 <= 
        ClusterEta34_0_Clust_fu_654_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        p_read38_read34_rea_fu_616_p3;
    ClusterEta34_0_Clust_fu_654_p3 <= 
        p_read39_read_fu_486_p3 when (tmp_38_reg_1198(0) = '1') else 
        p_read37_read_fu_430_p3;
    ClusterEta34_1_Clust_fu_914_p3 <= 
        ClusterEta32_0_Clust_fu_661_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        p_read36_read32_rea_fu_623_p3;
    ClusterEta35_0_Clust_fu_699_p3 <= 
        p_read32_read_fu_409_p3 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read34_read_fu_465_p3;
    ClusterEta35_1_Clust_fu_976_p3 <= 
        ClusterEta3743_0_Clu_fu_692_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterEta38_0_Clust_fu_730_p3;
    ClusterEta36_0_Clust_fu_737_p3 <= 
        p_read33_read_fu_437_p3 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read35_read_fu_493_p3;
    ClusterEta36_1_Clust_fu_968_p3 <= 
        ClusterEta38_0_Clust_fu_730_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterEta3743_0_Clu_fu_692_p3;
    ClusterEta3743_0_Clu_fu_692_p3 <= 
        p_read34_read_fu_465_p3 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read32_read_fu_409_p3;
    ClusterEta3743_1_Clu_fu_1030_p3 <= 
        ClusterEta35_0_Clust_fu_699_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterEta36_0_Clust_fu_737_p3;
    ClusterEta38_0_Clust_fu_730_p3 <= 
        p_read35_read_fu_493_p3 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read33_read_fu_437_p3;
    ClusterEta38_1_Clust_fu_1022_p3 <= 
        ClusterEta36_0_Clust_fu_737_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterEta35_0_Clust_fu_699_p3;
    ClusterEta43_0_Clust_fu_776_p3 <= 
        p_read_fu_528_p3 when (tmp_221_1_fu_758_p2(0) = '1') else 
        ap_const_lv16_0;
    ClusterEta44_0_rea_1_fu_1076_p3 <= 
        ClusterEta44_0_rea_fu_816_p3 when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ClusterEta43_0_Clust_fu_776_p3;
    ClusterEta44_0_rea_fu_816_p3 <= 
        p_read9_fu_574_p3 when (tmp_226_1_fu_798_p2(0) = '1') else 
        ap_const_lv16_0;
    ClusterEta45_0_Clust_fu_770_p2 <= (tmp_fu_536_p1 and not_tmp_221_1_fu_764_p2);
    ClusterEta45_1_Clust_fu_1084_p3 <= 
        ClusterEta43_0_Clust_fu_776_p3 when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ClusterEta44_0_rea_fu_816_p3;
    ClusterEta_1_Cluster_fu_868_p3 <= 
        p_read38_read34_rea_fu_616_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        ClusterEta34_0_Clust_fu_654_p3;
    ClusterPhi63_0_Clust_fu_675_p3 <= 
        p_read69_read_fu_444_p3 when (tmp_38_reg_1198(0) = '1') else 
        p_read71_read_fu_500_p3;
    ClusterPhi64_1_Clust_fu_938_p3 <= 
        p_read68_read64_rea_fu_637_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        ClusterPhi63_0_Clust_fu_675_p3;
    ClusterPhi65_0_Clust_1_fu_876_p3 <= 
        ClusterPhi65_0_Clust_fu_668_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        p_read70_read66_rea_fu_630_p3;
    ClusterPhi65_0_Clust_fu_668_p3 <= 
        p_read71_read_fu_500_p3 when (tmp_38_reg_1198(0) = '1') else 
        p_read69_read_fu_444_p3;
    ClusterPhi65_1_Clust_fu_930_p3 <= 
        ClusterPhi63_0_Clust_fu_675_p3 when (tmp_251_1_fu_892_p2(0) = '1') else 
        p_read68_read64_rea_fu_637_p3;
    ClusterPhi66_0_Clust_fu_713_p3 <= 
        p_read64_read_fu_423_p3 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read66_read_fu_479_p3;
    ClusterPhi66_1_Clust_fu_992_p3 <= 
        ClusterPhi68_0_Clust_fu_706_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterPhi69_0_Clust_fu_744_p3;
    ClusterPhi67_0_Clust_fu_751_p3 <= 
        p_read65_read_fu_451_p3 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read67_read_fu_507_p3;
    ClusterPhi67_1_Clust_fu_984_p3 <= 
        ClusterPhi69_0_Clust_fu_744_p3 when (tmp_251_2_fu_946_p2(0) = '1') else 
        ClusterPhi68_0_Clust_fu_706_p3;
    ClusterPhi68_0_Clust_fu_706_p3 <= 
        p_read66_read_fu_479_p3 when (tmp_211_1_reg_1208(0) = '1') else 
        p_read64_read_fu_423_p3;
    ClusterPhi68_1_Clust_fu_1046_p3 <= 
        ClusterPhi66_0_Clust_fu_713_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterPhi67_0_Clust_fu_751_p3;
    ClusterPhi69_0_Clust_fu_744_p3 <= 
        p_read67_read_fu_507_p3 when (tmp_216_1_reg_1218(0) = '1') else 
        p_read65_read_fu_451_p3;
    ClusterPhi69_1_Clust_fu_1038_p3 <= 
        ClusterPhi67_0_Clust_fu_751_p3 when (tmp_251_3_fu_1000_p2(0) = '1') else 
        ClusterPhi66_0_Clust_fu_713_p3;
    ClusterPhi74_0_Clust_fu_790_p3 <= 
        p_read8_fu_548_p3 when (tmp_221_1_fu_758_p2(0) = '1') else 
        ap_const_lv16_0;
    ClusterPhi75_0_rea_1_fu_1092_p3 <= 
        ClusterPhi75_0_rea_fu_830_p3 when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ClusterPhi74_0_Clust_fu_790_p3;
    ClusterPhi75_0_rea_fu_830_p3 <= 
        p_read1_fu_594_p3 when (tmp_226_1_fu_798_p2(0) = '1') else 
        ap_const_lv16_0;
    ClusterPhi76_0_Clust_fu_784_p2 <= (tmp_65_fu_556_p1 and not_tmp_221_1_fu_764_p2);
    ClusterPhi76_1_Clust_fu_1100_p3 <= 
        ClusterPhi74_0_Clust_fu_790_p3 when (tmp_256_3_fu_1054_p2(0) = '1') else 
        ClusterPhi75_0_rea_fu_830_p3;
    ClusterPhi_1_Cluster_fu_884_p3 <= 
        p_read70_read66_rea_fu_630_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        ClusterPhi65_0_Clust_fu_668_p3;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2 downto 2);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5 downto 5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_preg)
    begin
        if ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_preg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage5)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_bitonic16_fu_248_ap_return_0;
    ap_return_1 <= grp_bitonic16_fu_248_ap_return_1;
    ap_return_10 <= grp_bitonic16_fu_248_ap_return_10;
    ap_return_11 <= grp_bitonic16_fu_248_ap_return_11;
    ap_return_12 <= grp_bitonic16_fu_248_ap_return_12;
    ap_return_13 <= grp_bitonic16_fu_248_ap_return_13;
    ap_return_14 <= grp_bitonic16_fu_248_ap_return_14;
    ap_return_15 <= grp_bitonic16_fu_248_ap_return_15;
    ap_return_16 <= grp_bitonic16_fu_248_ap_return_16;
    ap_return_17 <= grp_bitonic16_fu_248_ap_return_17;
    ap_return_18 <= grp_bitonic16_fu_248_ap_return_18;
    ap_return_19 <= grp_bitonic16_fu_248_ap_return_19;
    ap_return_2 <= grp_bitonic16_fu_248_ap_return_2;
    ap_return_20 <= grp_bitonic16_fu_248_ap_return_20;
    ap_return_21 <= grp_bitonic16_fu_248_ap_return_21;
    ap_return_22 <= grp_bitonic16_fu_248_ap_return_22;
    ap_return_23 <= grp_bitonic16_fu_248_ap_return_23;
    ap_return_24 <= grp_bitonic16_fu_248_ap_return_24;
    ap_return_25 <= grp_bitonic16_fu_248_ap_return_25;
    ap_return_26 <= grp_bitonic16_fu_248_ap_return_26;
    ap_return_27 <= grp_bitonic16_fu_248_ap_return_27;
    ap_return_28 <= grp_bitonic16_fu_248_ap_return_28;
    ap_return_29 <= grp_bitonic16_fu_248_ap_return_29;
    ap_return_3 <= grp_bitonic16_fu_248_ap_return_3;
    ap_return_30 <= grp_bitonic16_fu_248_ap_return_30;
    ap_return_31 <= grp_bitonic16_fu_248_ap_return_31;
    ap_return_32 <= grp_bitonic16_fu_248_ap_return_32;
    ap_return_33 <= grp_bitonic16_fu_248_ap_return_33;
    ap_return_34 <= grp_bitonic16_fu_248_ap_return_34;
    ap_return_35 <= grp_bitonic16_fu_248_ap_return_35;
    ap_return_36 <= grp_bitonic16_fu_248_ap_return_36;
    ap_return_37 <= grp_bitonic16_fu_248_ap_return_37;
    ap_return_38 <= grp_bitonic16_fu_248_ap_return_38;
    ap_return_39 <= grp_bitonic16_fu_248_ap_return_39;
    ap_return_4 <= grp_bitonic16_fu_248_ap_return_4;
    ap_return_40 <= grp_bitonic16_fu_248_ap_return_40;
    ap_return_41 <= grp_bitonic16_fu_248_ap_return_41;
    ap_return_42 <= grp_bitonic16_fu_248_ap_return_42;
    ap_return_43 <= grp_bitonic16_fu_248_ap_return_43;
    ap_return_44 <= grp_bitonic16_fu_248_ap_return_44;
    ap_return_45 <= grp_bitonic16_fu_248_ap_return_45;
    ap_return_46 <= grp_bitonic16_fu_248_ap_return_46;
    ap_return_47 <= grp_bitonic16_fu_248_ap_return_47;
    ap_return_48 <= grp_bitonic16_fu_248_ap_return_48;
    ap_return_49 <= grp_bitonic16_fu_248_ap_return_49;
    ap_return_5 <= grp_bitonic16_fu_248_ap_return_5;
    ap_return_50 <= grp_bitonic16_fu_248_ap_return_50;
    ap_return_51 <= grp_bitonic16_fu_248_ap_return_51;
    ap_return_52 <= grp_bitonic16_fu_248_ap_return_52;
    ap_return_53 <= grp_bitonic16_fu_248_ap_return_53;
    ap_return_54 <= grp_bitonic16_fu_248_ap_return_54;
    ap_return_55 <= grp_bitonic16_fu_248_ap_return_55;
    ap_return_56 <= grp_bitonic16_fu_248_ap_return_56;
    ap_return_57 <= grp_bitonic16_fu_248_ap_return_57;
    ap_return_58 <= grp_bitonic16_fu_248_ap_return_58;
    ap_return_59 <= grp_bitonic16_fu_248_ap_return_59;
    ap_return_6 <= grp_bitonic16_fu_248_ap_return_6;
    ap_return_60 <= grp_bitonic16_fu_248_ap_return_60;
    ap_return_61 <= grp_bitonic16_fu_248_ap_return_61;
    ap_return_62 <= grp_bitonic16_fu_248_ap_return_62;
    ap_return_63 <= grp_bitonic16_fu_248_ap_return_63;
    ap_return_64 <= grp_bitonic16_fu_248_ap_return_64;
    ap_return_65 <= grp_bitonic16_fu_248_ap_return_65;
    ap_return_66 <= grp_bitonic16_fu_248_ap_return_66;
    ap_return_67 <= grp_bitonic16_fu_248_ap_return_67;
    ap_return_68 <= grp_bitonic16_fu_248_ap_return_68;
    ap_return_69 <= grp_bitonic16_fu_248_ap_return_69;
    ap_return_7 <= grp_bitonic16_fu_248_ap_return_7;
    ap_return_70 <= grp_bitonic16_fu_248_ap_return_70;
    ap_return_71 <= grp_bitonic16_fu_248_ap_return_71;
    ap_return_72 <= grp_bitonic16_fu_248_ap_return_72;
    ap_return_73 <= grp_bitonic16_fu_248_ap_return_73;
    ap_return_74 <= grp_bitonic16_fu_248_ap_return_74;
    ap_return_75 <= grp_bitonic16_fu_248_ap_return_75;
    ap_return_76 <= grp_bitonic16_fu_248_ap_return_76;
    ap_return_77 <= grp_bitonic16_fu_248_ap_return_77;
    ap_return_78 <= grp_bitonic16_fu_248_ap_return_78;
    ap_return_79 <= grp_bitonic16_fu_248_ap_return_79;
    ap_return_8 <= grp_bitonic16_fu_248_ap_return_8;
    ap_return_80 <= grp_bitonic16_fu_248_ap_return_80;
    ap_return_81 <= grp_bitonic16_fu_248_ap_return_81;
    ap_return_82 <= grp_bitonic16_fu_248_ap_return_82;
    ap_return_83 <= grp_bitonic16_fu_248_ap_return_83;
    ap_return_84 <= grp_bitonic16_fu_248_ap_return_84;
    ap_return_85 <= grp_bitonic16_fu_248_ap_return_85;
    ap_return_86 <= grp_bitonic16_fu_248_ap_return_86;
    ap_return_87 <= grp_bitonic16_fu_248_ap_return_87;
    ap_return_88 <= grp_bitonic16_fu_248_ap_return_88;
    ap_return_89 <= grp_bitonic16_fu_248_ap_return_89;
    ap_return_9 <= grp_bitonic16_fu_248_ap_return_9;
    grp_bitonic16_fu_248_ap_start <= ap_reg_grp_bitonic16_fu_248_ap_start;
    not_tmp_221_1_fu_764_p2 <= (tmp_221_1_fu_758_p2 xor ap_const_lv1_1);
    not_tmp_226_1_fu_804_p2 <= (tmp_226_1_fu_798_p2 xor ap_const_lv1_1);
    p_read1_fu_594_p3 <= 
        ap_const_lv16_0 when (tmp_198_1_fu_560_p2(0) = '1') else 
        ap_port_reg_ClusterPhi_9_read;
    p_read1_read5_fu_326_p3 <= 
        ClusterDeposits_1_r when (tmp_194_1_fu_312_p2(0) = '1') else 
        ClusterDeposits_5_r;
    p_read2_read6_fu_348_p3 <= 
        ClusterDeposits_2_r when (tmp_194_2_fu_334_p2(0) = '1') else 
        ClusterDeposits_6_r;
    p_read32_read_fu_409_p3 <= 
        ap_port_reg_ClusterEta_0_read when (tmp_s_reg_1108(0) = '1') else 
        ap_port_reg_ClusterEta_4_read;
    p_read33_read_fu_437_p3 <= 
        ap_port_reg_ClusterEta_1_read when (tmp_194_1_reg_1128(0) = '1') else 
        ap_port_reg_ClusterEta_5_read;
    p_read34_read_fu_465_p3 <= 
        ap_port_reg_ClusterEta_2_read when (tmp_194_2_reg_1148(0) = '1') else 
        ap_port_reg_ClusterEta_6_read;
    p_read35_read_fu_493_p3 <= 
        ap_port_reg_ClusterEta_3_read when (tmp_194_3_reg_1168(0) = '1') else 
        ap_port_reg_ClusterEta_7_read;
    p_read36_read32_rea_fu_623_p3 <= 
        p_read36_read_fu_402_p3 when (tmp_37_reg_1188(0) = '1') else 
        p_read38_read_fu_458_p3;
    p_read36_read_fu_402_p3 <= 
        ap_port_reg_ClusterEta_4_read when (tmp_s_reg_1108(0) = '1') else 
        ap_port_reg_ClusterEta_0_read;
    p_read37_read_fu_430_p3 <= 
        ap_port_reg_ClusterEta_5_read when (tmp_194_1_reg_1128(0) = '1') else 
        ap_port_reg_ClusterEta_1_read;
    p_read38_read34_rea_fu_616_p3 <= 
        p_read38_read_fu_458_p3 when (tmp_37_reg_1188(0) = '1') else 
        p_read36_read_fu_402_p3;
    p_read38_read_fu_458_p3 <= 
        ap_port_reg_ClusterEta_6_read when (tmp_194_2_reg_1148(0) = '1') else 
        ap_port_reg_ClusterEta_2_read;
    p_read39_read_fu_486_p3 <= 
        ap_port_reg_ClusterEta_7_read when (tmp_194_3_reg_1168(0) = '1') else 
        ap_port_reg_ClusterEta_3_read;
    p_read3_read7_fu_370_p3 <= 
        ClusterDeposits_3_r when (tmp_194_3_fu_356_p2(0) = '1') else 
        ClusterDeposits_7_r;
    p_read40_s_fu_520_p3 <= 
        ap_port_reg_ClusterEta_8_read when (tmp_36_fu_514_p2(0) = '1') else 
        ap_const_lv16_0;
    p_read41_s_fu_566_p3 <= 
        ap_port_reg_ClusterEta_9_read when (tmp_198_1_fu_560_p2(0) = '1') else 
        ap_const_lv16_0;
    p_read43_ClusterEta_fu_810_p2 <= (tmp_66_fu_582_p1 and not_tmp_226_1_fu_804_p2);
    p_read4_read_fu_296_p3 <= 
        ClusterDeposits_4_r when (tmp_s_fu_290_p2(0) = '1') else 
        ClusterDeposits_0_r;
    p_read4_read_read6_s_fu_611_p3 <= 
        p_read4_read_reg_1116 when (tmp_37_reg_1188(0) = '1') else 
        p_read6_read2_reg_1156;
    p_read5_read1_fu_318_p3 <= 
        ClusterDeposits_5_r when (tmp_194_1_fu_312_p2(0) = '1') else 
        ClusterDeposits_1_r;
    p_read64_read_fu_423_p3 <= 
        ap_port_reg_ClusterPhi_0_read when (tmp_s_reg_1108(0) = '1') else 
        ap_port_reg_ClusterPhi_4_read;
    p_read65_read_fu_451_p3 <= 
        ap_port_reg_ClusterPhi_1_read when (tmp_194_1_reg_1128(0) = '1') else 
        ap_port_reg_ClusterPhi_5_read;
    p_read66_read_fu_479_p3 <= 
        ap_port_reg_ClusterPhi_2_read when (tmp_194_2_reg_1148(0) = '1') else 
        ap_port_reg_ClusterPhi_6_read;
    p_read67_read_fu_507_p3 <= 
        ap_port_reg_ClusterPhi_3_read when (tmp_194_3_reg_1168(0) = '1') else 
        ap_port_reg_ClusterPhi_7_read;
    p_read68_read64_rea_fu_637_p3 <= 
        p_read68_read_fu_416_p3 when (tmp_37_reg_1188(0) = '1') else 
        p_read70_read_fu_472_p3;
    p_read68_read_fu_416_p3 <= 
        ap_port_reg_ClusterPhi_4_read when (tmp_s_reg_1108(0) = '1') else 
        ap_port_reg_ClusterPhi_0_read;
    p_read69_read_fu_444_p3 <= 
        ap_port_reg_ClusterPhi_5_read when (tmp_194_1_reg_1128(0) = '1') else 
        ap_port_reg_ClusterPhi_1_read;
    p_read6_read2_fu_340_p3 <= 
        ClusterDeposits_6_r when (tmp_194_2_fu_334_p2(0) = '1') else 
        ClusterDeposits_2_r;
    p_read6_read2_read4_fu_606_p3 <= 
        p_read6_read2_reg_1156 when (tmp_37_reg_1188(0) = '1') else 
        p_read4_read_reg_1116;
    p_read70_read66_rea_fu_630_p3 <= 
        p_read70_read_fu_472_p3 when (tmp_37_reg_1188(0) = '1') else 
        p_read68_read_fu_416_p3;
    p_read70_read_fu_472_p3 <= 
        ap_port_reg_ClusterPhi_6_read when (tmp_194_2_reg_1148(0) = '1') else 
        ap_port_reg_ClusterPhi_2_read;
    p_read71_read_fu_500_p3 <= 
        ap_port_reg_ClusterPhi_7_read when (tmp_194_3_reg_1168(0) = '1') else 
        ap_port_reg_ClusterPhi_3_read;
    p_read72_s_fu_540_p3 <= 
        ap_port_reg_ClusterPhi_8_read when (tmp_36_fu_514_p2(0) = '1') else 
        ap_const_lv16_0;
    p_read73_s_fu_586_p3 <= 
        ap_port_reg_ClusterPhi_9_read when (tmp_198_1_fu_560_p2(0) = '1') else 
        ap_const_lv16_0;
    p_read75_ClusterPhi_fu_824_p2 <= (tmp_67_fu_602_p1 and not_tmp_226_1_fu_804_p2);
    p_read7_read3_fu_362_p3 <= 
        ClusterDeposits_7_r when (tmp_194_3_fu_356_p2(0) = '1') else 
        ClusterDeposits_3_r;
    p_read8_fu_548_p3 <= 
        ap_const_lv16_0 when (tmp_36_fu_514_p2(0) = '1') else 
        ap_port_reg_ClusterPhi_8_read;
    p_read9_fu_574_p3 <= 
        ap_const_lv16_0 when (tmp_198_1_fu_560_p2(0) = '1') else 
        ap_port_reg_ClusterEta_9_read;
    p_read_fu_528_p3 <= 
        ap_const_lv16_0 when (tmp_36_fu_514_p2(0) = '1') else 
        ap_port_reg_ClusterEta_8_read;
    p_read_read4_fu_304_p3 <= 
        ClusterDeposits_0_r when (tmp_s_fu_290_p2(0) = '1') else 
        ClusterDeposits_4_r;
    sel_SEBB4_fu_844_p3 <= 
        ClusterDeposits3_0_C_fu_644_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        p_read6_read2_read4_fu_606_p3;
    sel_SEBB5_fu_852_p3 <= 
        p_read6_read2_read4_fu_606_p3 when (tmp_39_fu_838_p2(0) = '1') else 
        ClusterDeposits3_0_C_fu_644_p3;
    tmp_194_1_fu_312_p2 <= "1" when (unsigned(ClusterDeposits_1_r) < unsigned(ClusterDeposits_5_r)) else "0";
    tmp_194_2_fu_334_p2 <= "1" when (unsigned(ClusterDeposits_2_r) < unsigned(ClusterDeposits_6_r)) else "0";
    tmp_194_3_fu_356_p2 <= "1" when (unsigned(ClusterDeposits_3_r) < unsigned(ClusterDeposits_7_r)) else "0";
    tmp_198_1_fu_560_p2 <= "1" when (ap_port_reg_ClusterDeposits_9_r = ap_const_lv16_0) else "0";
    tmp_211_1_fu_390_p2 <= "1" when (unsigned(p_read_read4_fu_304_p3) < unsigned(p_read2_read6_fu_348_p3)) else "0";
    tmp_216_1_fu_396_p2 <= "1" when (unsigned(p_read1_read5_fu_326_p3) < unsigned(p_read3_read7_fu_370_p3)) else "0";
    tmp_221_1_fu_758_p2 <= "0" when (ap_port_reg_ClusterDeposits_8_r = ap_const_lv16_0) else "1";
    tmp_226_1_fu_798_p2 <= "0" when (ap_port_reg_ClusterDeposits_9_r = ap_const_lv16_0) else "1";
    tmp_251_1_fu_892_p2 <= "1" when (unsigned(p_read4_read_read6_s_fu_611_p3) < unsigned(ClusterDeposits12_0_s_fu_649_p3)) else "0";
    tmp_251_2_fu_946_p2 <= "1" when (unsigned(ClusterDeposits6_0_C_fu_682_p3) < unsigned(ClusterDeposits7_0_C_fu_720_p3)) else "0";
    tmp_251_3_fu_1000_p2 <= "1" when (unsigned(ClusterDeposits4_0_C_fu_687_p3) < unsigned(ClusterDeposits5_0_C_fu_725_p3)) else "0";
    tmp_256_3_fu_1054_p2 <= "1" when (unsigned(ap_port_reg_ClusterDeposits_8_r) > unsigned(ap_port_reg_ClusterDeposits_9_r)) else "0";
    tmp_36_fu_514_p2 <= "1" when (ap_port_reg_ClusterDeposits_8_r = ap_const_lv16_0) else "0";
    tmp_37_fu_378_p2 <= "1" when (unsigned(p_read4_read_fu_296_p3) < unsigned(p_read6_read2_fu_340_p3)) else "0";
    tmp_38_fu_384_p2 <= "1" when (unsigned(p_read5_read1_fu_318_p3) < unsigned(p_read7_read3_fu_362_p3)) else "0";
    tmp_39_fu_838_p2 <= "1" when (unsigned(p_read6_read2_read4_fu_606_p3) < unsigned(ClusterDeposits3_0_C_fu_644_p3)) else "0";
    tmp_65_fu_556_p1 <= p_read8_fu_548_p3(1 - 1 downto 0);
    tmp_66_fu_582_p1 <= p_read9_fu_574_p3(1 - 1 downto 0);
    tmp_67_fu_602_p1 <= p_read1_fu_594_p3(1 - 1 downto 0);
    tmp_fu_536_p1 <= p_read_fu_528_p3(1 - 1 downto 0);
    tmp_s_fu_290_p2 <= "1" when (unsigned(ClusterDeposits_0_r) < unsigned(ClusterDeposits_4_r)) else "0";
end behav;
