-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bitonic32 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ClusterDeposits_0_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_1_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_2_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_3_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_4_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_5_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_6_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_7_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_8_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterDeposits_9_r : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_10_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_11_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_12_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ClusterEta_13_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ClusterEta_14_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterEta_15_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_5_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_6_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_7_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_8_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_9_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_10_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_11_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_12_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ClusterPhi_13_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ClusterPhi_14_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ClusterPhi_15_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_50 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_51 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_52 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_53 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_54 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_55 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_56 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_57 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_58 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_59 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_60 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_61 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_62 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_63 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_64 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_65 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_66 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_67 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_68 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_69 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_70 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_71 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_72 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_73 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_74 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_75 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_76 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_77 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_78 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_79 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_80 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_81 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_82 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_83 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_84 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_85 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_86 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_87 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_88 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_89 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of bitonic32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_s_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1634 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read8_read_fu_350_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read8_read_reg_1642 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_read8_fu_358_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_read8_reg_1649 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_342_1_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_342_1_reg_1656 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read9_read1_fu_372_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read9_read1_reg_1664 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_read9_fu_380_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read1_read9_reg_1671 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_40_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_reg_1678 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ClusterDeposits4_1_C_fu_393_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_1_C_reg_1686 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits_1_Cl_fu_400_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits_1_Cl_reg_1692 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_350_1_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_350_1_reg_1698 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterDeposits5_1_C_fu_412_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_1_C_reg_1706 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits12_1_s_fu_419_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits12_1_s_reg_1712 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_350_2_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_350_2_reg_1718 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterDeposits6_1_C_fu_432_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_1_C_reg_1726 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_1_C_fu_440_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_1_C_reg_1732 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_350_3_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_350_3_reg_1738 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterDeposits7_1_C_fu_454_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_1_C_reg_1746 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_1_C_fu_462_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_1_C_reg_1752 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_41_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_reg_1758 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_reg_1768 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_367_1_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_367_1_reg_1778 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_372_1_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_372_1_reg_1788 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_ClusterDeposits_2_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_3_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_4_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_5_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_6_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterDeposits_7_r : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_0_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_1_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_2_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_3_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_4_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_5_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_6_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_7_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_8_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_9_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_10_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_11_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_12_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_ClusterEta_13_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_ClusterEta_14_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterEta_15_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_0_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_1_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_2_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_3_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_4_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_5_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_6_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_7_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_8_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_9_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_10_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_11_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_12_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_ClusterPhi_13_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_ClusterPhi_14_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_ClusterPhi_15_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_read40_read_fu_510_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read72_read_fu_524_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read41_read_fu_538_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read73_read_fu_552_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_1_Clu_fu_622_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_1_Clust_fu_566_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_1_Clust_fu_636_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_1_Clust_fu_580_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta38_1_Clust_fu_650_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta36_1_Clust_fu_594_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_1_Clust_fu_664_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_1_Clust_fu_608_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta33_1_Clust_fu_629_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_1_Cluster_fu_573_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi64_1_Clust_fu_643_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_1_Cluster_fu_587_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_1_Clust_fu_657_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta32_1_Clust_fu_601_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_1_Clust_fu_671_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi63_1_Clust_fu_615_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_2_C_fu_678_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_2_C_fu_716_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_43_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta34_2_Clust_fu_726_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta33_2_Clust_fu_688_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_2_Clust_fu_740_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi64_2_Clust_fu_702_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits_2_Cl_fu_683_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits12_2_s_fu_721_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_377_1_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta32_2_Clust_fu_733_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_2_Cluster_fu_695_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi63_2_Clust_fu_747_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_2_Cluster_fu_709_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_2_C_fu_754_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_2_C_fu_792_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_377_2_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta38_2_Clust_fu_802_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_2_Clu_fu_764_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_2_Clust_fu_816_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_2_Clust_fu_778_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_2_C_fu_759_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_2_C_fu_797_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_377_3_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ClusterEta36_2_Clust_fu_809_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_2_Clust_fu_771_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_2_Clust_fu_823_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_2_Clust_fu_785_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_377_4_fu_1046_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read33_read_fu_545_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read32_read_fu_517_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read65_read_fu_559_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read64_read_fu_531_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits12_3_s_fu_836_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits_3_Cl_fu_844_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits3_3_C_fu_890_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits2_3_C_fu_898_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits5_3_C_fu_944_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits4_3_C_fu_952_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits7_3_C_fu_998_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits6_3_C_fu_1006_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits9_3_C_fu_1050_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterDeposits8_3_C_fu_1056_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta32_3_Clust_fu_852_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_3_Cluster_fu_860_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta34_3_Clust_fu_906_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta33_3_Clust_fu_914_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta36_3_Clust_fu_960_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta35_3_Clust_fu_968_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta38_3_Clust_fu_1014_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta3743_3_Clu_fu_1022_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta40_3_Clust_fu_1062_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta39_3_Clust_fu_1070_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_12_read_s_fu_506_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterEta_13_read_s_fu_502_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi63_3_Clust_fu_868_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_3_Cluster_fu_876_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi65_3_Clust_fu_922_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi64_3_Clust_fu_930_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi67_3_Clust_fu_976_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi66_3_Clust_fu_984_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi69_3_Clust_fu_1030_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi68_3_Clust_fu_1038_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi71_3_Clust_fu_1078_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi7078_3_Clu_fu_1086_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_12_read_s_fu_498_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ClusterPhi_13_read_s_fu_494_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_state2))) then
                ClusterDeposits12_1_s_reg_1712 <= ClusterDeposits12_1_s_fu_419_p3;
                ClusterDeposits2_1_C_reg_1732 <= ClusterDeposits2_1_C_fu_440_p3;
                ClusterDeposits3_1_C_reg_1752 <= ClusterDeposits3_1_C_fu_462_p3;
                ClusterDeposits4_1_C_reg_1686 <= ClusterDeposits4_1_C_fu_393_p3;
                ClusterDeposits5_1_C_reg_1706 <= ClusterDeposits5_1_C_fu_412_p3;
                ClusterDeposits6_1_C_reg_1726 <= ClusterDeposits6_1_C_fu_432_p3;
                ClusterDeposits7_1_C_reg_1746 <= ClusterDeposits7_1_C_fu_454_p3;
                ClusterDeposits_1_Cl_reg_1692 <= ClusterDeposits_1_Cl_fu_400_p3;
                tmp_350_1_reg_1698 <= tmp_350_1_fu_407_p2;
                tmp_350_2_reg_1718 <= tmp_350_2_fu_426_p2;
                tmp_350_3_reg_1738 <= tmp_350_3_fu_448_p2;
                tmp_367_1_reg_1778 <= tmp_367_1_fu_482_p2;
                tmp_372_1_reg_1788 <= tmp_372_1_fu_488_p2;
                tmp_40_reg_1678 <= tmp_40_fu_388_p2;
                tmp_41_reg_1758 <= tmp_41_fu_470_p2;
                tmp_42_reg_1768 <= tmp_42_fu_476_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then
                ap_port_reg_ClusterDeposits_2_r <= ClusterDeposits_2_r;
                ap_port_reg_ClusterDeposits_3_r <= ClusterDeposits_3_r;
                ap_port_reg_ClusterDeposits_4_r <= ClusterDeposits_4_r;
                ap_port_reg_ClusterDeposits_5_r <= ClusterDeposits_5_r;
                ap_port_reg_ClusterDeposits_6_r <= ClusterDeposits_6_r;
                ap_port_reg_ClusterDeposits_7_r <= ClusterDeposits_7_r;
                ap_port_reg_ClusterEta_0_read <= ClusterEta_0_read;
                ap_port_reg_ClusterEta_10_read <= ClusterEta_10_read;
                ap_port_reg_ClusterEta_11_read <= ClusterEta_11_read;
                ap_port_reg_ClusterEta_12_read <= ClusterEta_12_read;
                ap_port_reg_ClusterEta_13_read <= ClusterEta_13_read;
                ap_port_reg_ClusterEta_14_read <= ClusterEta_14_read;
                ap_port_reg_ClusterEta_15_read <= ClusterEta_15_read;
                ap_port_reg_ClusterEta_1_read <= ClusterEta_1_read;
                ap_port_reg_ClusterEta_2_read <= ClusterEta_2_read;
                ap_port_reg_ClusterEta_3_read <= ClusterEta_3_read;
                ap_port_reg_ClusterEta_4_read <= ClusterEta_4_read;
                ap_port_reg_ClusterEta_5_read <= ClusterEta_5_read;
                ap_port_reg_ClusterEta_6_read <= ClusterEta_6_read;
                ap_port_reg_ClusterEta_7_read <= ClusterEta_7_read;
                ap_port_reg_ClusterEta_8_read <= ClusterEta_8_read;
                ap_port_reg_ClusterEta_9_read <= ClusterEta_9_read;
                ap_port_reg_ClusterPhi_0_read <= ClusterPhi_0_read;
                ap_port_reg_ClusterPhi_10_read <= ClusterPhi_10_read;
                ap_port_reg_ClusterPhi_11_read <= ClusterPhi_11_read;
                ap_port_reg_ClusterPhi_12_read <= ClusterPhi_12_read;
                ap_port_reg_ClusterPhi_13_read <= ClusterPhi_13_read;
                ap_port_reg_ClusterPhi_14_read <= ClusterPhi_14_read;
                ap_port_reg_ClusterPhi_15_read <= ClusterPhi_15_read;
                ap_port_reg_ClusterPhi_1_read <= ClusterPhi_1_read;
                ap_port_reg_ClusterPhi_2_read <= ClusterPhi_2_read;
                ap_port_reg_ClusterPhi_3_read <= ClusterPhi_3_read;
                ap_port_reg_ClusterPhi_4_read <= ClusterPhi_4_read;
                ap_port_reg_ClusterPhi_5_read <= ClusterPhi_5_read;
                ap_port_reg_ClusterPhi_6_read <= ClusterPhi_6_read;
                ap_port_reg_ClusterPhi_7_read <= ClusterPhi_7_read;
                ap_port_reg_ClusterPhi_8_read <= ClusterPhi_8_read;
                ap_port_reg_ClusterPhi_9_read <= ClusterPhi_9_read;
                p_read1_read9_reg_1671 <= p_read1_read9_fu_380_p3;
                p_read8_read_reg_1642 <= p_read8_read_fu_350_p3;
                p_read9_read1_reg_1664 <= p_read9_read1_fu_372_p3;
                p_read_read8_reg_1649 <= p_read_read8_fu_358_p3;
                tmp_342_1_reg_1656 <= tmp_342_1_fu_366_p2;
                tmp_s_reg_1634 <= tmp_s_fu_344_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ClusterDeposits12_1_s_fu_419_p3 <= 
        p_read9_read1_reg_1664 when (tmp_350_1_fu_407_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_5_r;
    ClusterDeposits12_2_s_fu_721_p3 <= 
        ClusterDeposits5_1_C_reg_1706 when (tmp_42_reg_1768(0) = '1') else 
        ClusterDeposits7_1_C_reg_1746;
    ClusterDeposits12_3_s_fu_836_p3 <= 
        ClusterDeposits3_2_C_fu_716_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterDeposits2_2_C_fu_678_p3;
    ClusterDeposits2_1_C_fu_440_p3 <= 
        ap_port_reg_ClusterDeposits_2_r when (tmp_350_2_fu_426_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_6_r;
    ClusterDeposits2_2_C_fu_678_p3 <= 
        ClusterDeposits6_1_C_reg_1726 when (tmp_41_reg_1758(0) = '1') else 
        ClusterDeposits4_1_C_reg_1686;
    ClusterDeposits2_3_C_fu_898_p3 <= 
        ClusterDeposits_2_Cl_fu_683_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterDeposits12_2_s_fu_721_p3;
    ClusterDeposits3_1_C_fu_462_p3 <= 
        ap_port_reg_ClusterDeposits_3_r when (tmp_350_3_fu_448_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_7_r;
    ClusterDeposits3_2_C_fu_716_p3 <= 
        ClusterDeposits7_1_C_reg_1746 when (tmp_42_reg_1768(0) = '1') else 
        ClusterDeposits5_1_C_reg_1706;
    ClusterDeposits3_3_C_fu_890_p3 <= 
        ClusterDeposits12_2_s_fu_721_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterDeposits_2_Cl_fu_683_p3;
    ClusterDeposits4_1_C_fu_393_p3 <= 
        ap_port_reg_ClusterDeposits_4_r when (tmp_40_fu_388_p2(0) = '1') else 
        p_read8_read_reg_1642;
    ClusterDeposits4_2_C_fu_759_p3 <= 
        ClusterDeposits_1_Cl_reg_1692 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterDeposits2_1_C_reg_1732;
    ClusterDeposits4_3_C_fu_952_p3 <= 
        ClusterDeposits6_2_C_fu_754_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterDeposits7_2_C_fu_792_p3;
    ClusterDeposits5_1_C_fu_412_p3 <= 
        ap_port_reg_ClusterDeposits_5_r when (tmp_350_1_fu_407_p2(0) = '1') else 
        p_read9_read1_reg_1664;
    ClusterDeposits5_2_C_fu_797_p3 <= 
        ClusterDeposits12_1_s_reg_1712 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterDeposits3_1_C_reg_1752;
    ClusterDeposits5_3_C_fu_944_p3 <= 
        ClusterDeposits7_2_C_fu_792_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterDeposits6_2_C_fu_754_p3;
    ClusterDeposits6_1_C_fu_432_p3 <= 
        ap_port_reg_ClusterDeposits_6_r when (tmp_350_2_fu_426_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_2_r;
    ClusterDeposits6_2_C_fu_754_p3 <= 
        ClusterDeposits2_1_C_reg_1732 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterDeposits_1_Cl_reg_1692;
    ClusterDeposits6_3_C_fu_1006_p3 <= 
        ClusterDeposits4_2_C_fu_759_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterDeposits5_2_C_fu_797_p3;
    ClusterDeposits7_1_C_fu_454_p3 <= 
        ap_port_reg_ClusterDeposits_7_r when (tmp_350_3_fu_448_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_3_r;
    ClusterDeposits7_2_C_fu_792_p3 <= 
        ClusterDeposits3_1_C_reg_1752 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterDeposits12_1_s_reg_1712;
    ClusterDeposits7_3_C_fu_998_p3 <= 
        ClusterDeposits5_2_C_fu_797_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterDeposits4_2_C_fu_759_p3;
    ClusterDeposits8_3_C_fu_1056_p3 <= 
        p_read_read8_reg_1649 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read1_read9_reg_1671;
    ClusterDeposits9_3_C_fu_1050_p3 <= 
        p_read1_read9_reg_1671 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read_read8_reg_1649;
    ClusterDeposits_1_Cl_fu_400_p3 <= 
        p_read8_read_reg_1642 when (tmp_40_fu_388_p2(0) = '1') else 
        ap_port_reg_ClusterDeposits_4_r;
    ClusterDeposits_2_Cl_fu_683_p3 <= 
        ClusterDeposits4_1_C_reg_1686 when (tmp_41_reg_1758(0) = '1') else 
        ClusterDeposits6_1_C_reg_1726;
    ClusterDeposits_3_Cl_fu_844_p3 <= 
        ClusterDeposits2_2_C_fu_678_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterDeposits3_2_C_fu_716_p3;
    ClusterEta32_1_Clust_fu_601_p3 <= 
        p_read41_read_fu_538_p3 when (tmp_350_1_reg_1698(0) = '1') else 
        ap_port_reg_ClusterEta_5_read;
    ClusterEta32_2_Clust_fu_733_p3 <= 
        ClusterEta36_1_Clust_fu_594_p3 when (tmp_42_reg_1768(0) = '1') else 
        ClusterEta38_1_Clust_fu_650_p3;
    ClusterEta32_3_Clust_fu_852_p3 <= 
        ClusterEta34_2_Clust_fu_726_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterEta33_2_Clust_fu_688_p3;
    ClusterEta33_1_Clust_fu_629_p3 <= 
        ap_port_reg_ClusterEta_2_read when (tmp_350_2_reg_1718(0) = '1') else 
        ap_port_reg_ClusterEta_6_read;
    ClusterEta33_2_Clust_fu_688_p3 <= 
        ClusterEta3743_1_Clu_fu_622_p3 when (tmp_41_reg_1758(0) = '1') else 
        ClusterEta35_1_Clust_fu_566_p3;
    ClusterEta33_3_Clust_fu_914_p3 <= 
        ClusterEta_2_Cluster_fu_695_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterEta32_2_Clust_fu_733_p3;
    ClusterEta34_1_Clust_fu_657_p3 <= 
        ap_port_reg_ClusterEta_3_read when (tmp_350_3_reg_1738(0) = '1') else 
        ap_port_reg_ClusterEta_7_read;
    ClusterEta34_2_Clust_fu_726_p3 <= 
        ClusterEta38_1_Clust_fu_650_p3 when (tmp_42_reg_1768(0) = '1') else 
        ClusterEta36_1_Clust_fu_594_p3;
    ClusterEta34_3_Clust_fu_906_p3 <= 
        ClusterEta32_2_Clust_fu_733_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterEta_2_Cluster_fu_695_p3;
    ClusterEta35_1_Clust_fu_566_p3 <= 
        ap_port_reg_ClusterEta_4_read when (tmp_40_reg_1678(0) = '1') else 
        p_read40_read_fu_510_p3;
    ClusterEta35_2_Clust_fu_771_p3 <= 
        ClusterEta_1_Cluster_fu_573_p3 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterEta33_1_Clust_fu_629_p3;
    ClusterEta35_3_Clust_fu_968_p3 <= 
        ClusterEta3743_2_Clu_fu_764_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterEta38_2_Clust_fu_802_p3;
    ClusterEta36_1_Clust_fu_594_p3 <= 
        ap_port_reg_ClusterEta_5_read when (tmp_350_1_reg_1698(0) = '1') else 
        p_read41_read_fu_538_p3;
    ClusterEta36_2_Clust_fu_809_p3 <= 
        ClusterEta32_1_Clust_fu_601_p3 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterEta34_1_Clust_fu_657_p3;
    ClusterEta36_3_Clust_fu_960_p3 <= 
        ClusterEta38_2_Clust_fu_802_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterEta3743_2_Clu_fu_764_p3;
    ClusterEta3743_1_Clu_fu_622_p3 <= 
        ap_port_reg_ClusterEta_6_read when (tmp_350_2_reg_1718(0) = '1') else 
        ap_port_reg_ClusterEta_2_read;
    ClusterEta3743_2_Clu_fu_764_p3 <= 
        ClusterEta33_1_Clust_fu_629_p3 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterEta_1_Cluster_fu_573_p3;
    ClusterEta3743_3_Clu_fu_1022_p3 <= 
        ClusterEta35_2_Clust_fu_771_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterEta36_2_Clust_fu_809_p3;
    ClusterEta38_1_Clust_fu_650_p3 <= 
        ap_port_reg_ClusterEta_7_read when (tmp_350_3_reg_1738(0) = '1') else 
        ap_port_reg_ClusterEta_3_read;
    ClusterEta38_2_Clust_fu_802_p3 <= 
        ClusterEta34_1_Clust_fu_657_p3 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterEta32_1_Clust_fu_601_p3;
    ClusterEta38_3_Clust_fu_1014_p3 <= 
        ClusterEta36_2_Clust_fu_809_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterEta35_2_Clust_fu_771_p3;
    ClusterEta39_3_Clust_fu_1070_p3 <= 
        p_read32_read_fu_517_p3 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read33_read_fu_545_p3;
    ClusterEta40_3_Clust_fu_1062_p3 <= 
        p_read33_read_fu_545_p3 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read32_read_fu_517_p3;
    ClusterEta_12_read_s_fu_506_p1 <= std_logic_vector(resize(unsigned(ap_port_reg_ClusterEta_12_read),16));
    ClusterEta_13_read_s_fu_502_p1 <= std_logic_vector(resize(unsigned(ap_port_reg_ClusterEta_13_read),16));
    ClusterEta_1_Cluster_fu_573_p3 <= 
        p_read40_read_fu_510_p3 when (tmp_40_reg_1678(0) = '1') else 
        ap_port_reg_ClusterEta_4_read;
    ClusterEta_2_Cluster_fu_695_p3 <= 
        ClusterEta35_1_Clust_fu_566_p3 when (tmp_41_reg_1758(0) = '1') else 
        ClusterEta3743_1_Clu_fu_622_p3;
    ClusterEta_3_Cluster_fu_860_p3 <= 
        ClusterEta33_2_Clust_fu_688_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterEta34_2_Clust_fu_726_p3;
    ClusterPhi63_1_Clust_fu_615_p3 <= 
        p_read73_read_fu_552_p3 when (tmp_350_1_reg_1698(0) = '1') else 
        ap_port_reg_ClusterPhi_5_read;
    ClusterPhi63_2_Clust_fu_747_p3 <= 
        ClusterPhi67_1_Clust_fu_608_p3 when (tmp_42_reg_1768(0) = '1') else 
        ClusterPhi69_1_Clust_fu_664_p3;
    ClusterPhi63_3_Clust_fu_868_p3 <= 
        ClusterPhi65_2_Clust_fu_740_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterPhi64_2_Clust_fu_702_p3;
    ClusterPhi64_1_Clust_fu_643_p3 <= 
        ap_port_reg_ClusterPhi_2_read when (tmp_350_2_reg_1718(0) = '1') else 
        ap_port_reg_ClusterPhi_6_read;
    ClusterPhi64_2_Clust_fu_702_p3 <= 
        ClusterPhi68_1_Clust_fu_636_p3 when (tmp_41_reg_1758(0) = '1') else 
        ClusterPhi66_1_Clust_fu_580_p3;
    ClusterPhi64_3_Clust_fu_930_p3 <= 
        ClusterPhi_2_Cluster_fu_709_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterPhi63_2_Clust_fu_747_p3;
    ClusterPhi65_1_Clust_fu_671_p3 <= 
        ap_port_reg_ClusterPhi_3_read when (tmp_350_3_reg_1738(0) = '1') else 
        ap_port_reg_ClusterPhi_7_read;
    ClusterPhi65_2_Clust_fu_740_p3 <= 
        ClusterPhi69_1_Clust_fu_664_p3 when (tmp_42_reg_1768(0) = '1') else 
        ClusterPhi67_1_Clust_fu_608_p3;
    ClusterPhi65_3_Clust_fu_922_p3 <= 
        ClusterPhi63_2_Clust_fu_747_p3 when (tmp_377_1_fu_884_p2(0) = '1') else 
        ClusterPhi_2_Cluster_fu_709_p3;
    ClusterPhi66_1_Clust_fu_580_p3 <= 
        ap_port_reg_ClusterPhi_4_read when (tmp_40_reg_1678(0) = '1') else 
        p_read72_read_fu_524_p3;
    ClusterPhi66_2_Clust_fu_785_p3 <= 
        ClusterPhi_1_Cluster_fu_587_p3 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterPhi64_1_Clust_fu_643_p3;
    ClusterPhi66_3_Clust_fu_984_p3 <= 
        ClusterPhi68_2_Clust_fu_778_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterPhi69_2_Clust_fu_816_p3;
    ClusterPhi67_1_Clust_fu_608_p3 <= 
        ap_port_reg_ClusterPhi_5_read when (tmp_350_1_reg_1698(0) = '1') else 
        p_read73_read_fu_552_p3;
    ClusterPhi67_2_Clust_fu_823_p3 <= 
        ClusterPhi63_1_Clust_fu_615_p3 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterPhi65_1_Clust_fu_671_p3;
    ClusterPhi67_3_Clust_fu_976_p3 <= 
        ClusterPhi69_2_Clust_fu_816_p3 when (tmp_377_2_fu_938_p2(0) = '1') else 
        ClusterPhi68_2_Clust_fu_778_p3;
    ClusterPhi68_1_Clust_fu_636_p3 <= 
        ap_port_reg_ClusterPhi_6_read when (tmp_350_2_reg_1718(0) = '1') else 
        ap_port_reg_ClusterPhi_2_read;
    ClusterPhi68_2_Clust_fu_778_p3 <= 
        ClusterPhi64_1_Clust_fu_643_p3 when (tmp_367_1_reg_1778(0) = '1') else 
        ClusterPhi_1_Cluster_fu_587_p3;
    ClusterPhi68_3_Clust_fu_1038_p3 <= 
        ClusterPhi66_2_Clust_fu_785_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterPhi67_2_Clust_fu_823_p3;
    ClusterPhi69_1_Clust_fu_664_p3 <= 
        ap_port_reg_ClusterPhi_7_read when (tmp_350_3_reg_1738(0) = '1') else 
        ap_port_reg_ClusterPhi_3_read;
    ClusterPhi69_2_Clust_fu_816_p3 <= 
        ClusterPhi65_1_Clust_fu_671_p3 when (tmp_372_1_reg_1788(0) = '1') else 
        ClusterPhi63_1_Clust_fu_615_p3;
    ClusterPhi69_3_Clust_fu_1030_p3 <= 
        ClusterPhi67_2_Clust_fu_823_p3 when (tmp_377_3_fu_992_p2(0) = '1') else 
        ClusterPhi66_2_Clust_fu_785_p3;
    ClusterPhi7078_3_Clu_fu_1086_p3 <= 
        p_read64_read_fu_531_p3 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read65_read_fu_559_p3;
    ClusterPhi71_3_Clust_fu_1078_p3 <= 
        p_read65_read_fu_559_p3 when (tmp_377_4_fu_1046_p2(0) = '1') else 
        p_read64_read_fu_531_p3;
    ClusterPhi_12_read_s_fu_498_p1 <= std_logic_vector(resize(unsigned(ap_port_reg_ClusterPhi_12_read),16));
    ClusterPhi_13_read_s_fu_494_p1 <= std_logic_vector(resize(unsigned(ap_port_reg_ClusterPhi_13_read),16));
    ClusterPhi_1_Cluster_fu_587_p3 <= 
        p_read72_read_fu_524_p3 when (tmp_40_reg_1678(0) = '1') else 
        ap_port_reg_ClusterPhi_4_read;
    ClusterPhi_2_Cluster_fu_709_p3 <= 
        ClusterPhi66_1_Clust_fu_580_p3 when (tmp_41_reg_1758(0) = '1') else 
        ClusterPhi68_1_Clust_fu_636_p3;
    ClusterPhi_3_Cluster_fu_876_p3 <= 
        ClusterPhi64_2_Clust_fu_702_p3 when (tmp_43_fu_830_p2(0) = '1') else 
        ClusterPhi65_2_Clust_fu_740_p3;
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2 downto 2);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1)) or ((ap_const_lv1_1 = ap_CS_fsm_state3)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= ClusterDeposits12_3_s_fu_836_p3;
    ap_return_1 <= ClusterDeposits_3_Cl_fu_844_p3;
    ap_return_10 <= ap_const_lv16_0;
    ap_return_11 <= ap_const_lv16_0;
    ap_return_12 <= ap_const_lv16_0;
    ap_return_13 <= ap_const_lv16_0;
    ap_return_14 <= ap_const_lv16_0;
    ap_return_15 <= ap_const_lv16_0;
    ap_return_16 <= ap_const_lv16_0;
    ap_return_17 <= ap_const_lv16_0;
    ap_return_18 <= ap_const_lv16_0;
    ap_return_19 <= ap_const_lv16_0;
    ap_return_2 <= ClusterDeposits3_3_C_fu_890_p3;
    ap_return_20 <= ap_const_lv16_0;
    ap_return_21 <= ap_const_lv16_0;
    ap_return_22 <= ap_const_lv16_0;
    ap_return_23 <= ap_const_lv16_0;
    ap_return_24 <= ap_const_lv16_0;
    ap_return_25 <= ap_const_lv16_0;
    ap_return_26 <= ap_const_lv16_0;
    ap_return_27 <= ap_const_lv16_0;
    ap_return_28 <= ap_const_lv16_0;
    ap_return_29 <= ap_const_lv16_0;
    ap_return_3 <= ClusterDeposits2_3_C_fu_898_p3;
    ap_return_30 <= ClusterEta32_3_Clust_fu_852_p3;
    ap_return_31 <= ClusterEta_3_Cluster_fu_860_p3;
    ap_return_32 <= ClusterEta34_3_Clust_fu_906_p3;
    ap_return_33 <= ClusterEta33_3_Clust_fu_914_p3;
    ap_return_34 <= ClusterEta36_3_Clust_fu_960_p3;
    ap_return_35 <= ClusterEta35_3_Clust_fu_968_p3;
    ap_return_36 <= ClusterEta38_3_Clust_fu_1014_p3;
    ap_return_37 <= ClusterEta3743_3_Clu_fu_1022_p3;
    ap_return_38 <= ClusterEta40_3_Clust_fu_1062_p3;
    ap_return_39 <= ClusterEta39_3_Clust_fu_1070_p3;
    ap_return_4 <= ClusterDeposits5_3_C_fu_944_p3;
    ap_return_40 <= ap_port_reg_ClusterEta_10_read;
    ap_return_41 <= ap_port_reg_ClusterEta_11_read;
    ap_return_42 <= ClusterEta_12_read_s_fu_506_p1;
    ap_return_43 <= ClusterEta_13_read_s_fu_502_p1;
    ap_return_44 <= ap_port_reg_ClusterEta_14_read;
    ap_return_45 <= ap_port_reg_ClusterEta_15_read;
    ap_return_46 <= ap_const_lv16_0;
    ap_return_47 <= ap_const_lv16_0;
    ap_return_48 <= ap_const_lv16_0;
    ap_return_49 <= ap_const_lv16_0;
    ap_return_5 <= ClusterDeposits4_3_C_fu_952_p3;
    ap_return_50 <= ap_const_lv16_0;
    ap_return_51 <= ap_const_lv16_0;
    ap_return_52 <= ap_const_lv16_0;
    ap_return_53 <= ap_const_lv16_0;
    ap_return_54 <= ap_const_lv16_0;
    ap_return_55 <= ap_const_lv16_0;
    ap_return_56 <= ap_const_lv16_0;
    ap_return_57 <= ap_const_lv16_0;
    ap_return_58 <= ap_const_lv16_0;
    ap_return_59 <= ap_const_lv16_0;
    ap_return_6 <= ClusterDeposits7_3_C_fu_998_p3;
    ap_return_60 <= ClusterPhi63_3_Clust_fu_868_p3;
    ap_return_61 <= ClusterPhi_3_Cluster_fu_876_p3;
    ap_return_62 <= ClusterPhi65_3_Clust_fu_922_p3;
    ap_return_63 <= ClusterPhi64_3_Clust_fu_930_p3;
    ap_return_64 <= ClusterPhi67_3_Clust_fu_976_p3;
    ap_return_65 <= ClusterPhi66_3_Clust_fu_984_p3;
    ap_return_66 <= ClusterPhi69_3_Clust_fu_1030_p3;
    ap_return_67 <= ClusterPhi68_3_Clust_fu_1038_p3;
    ap_return_68 <= ClusterPhi71_3_Clust_fu_1078_p3;
    ap_return_69 <= ClusterPhi7078_3_Clu_fu_1086_p3;
    ap_return_7 <= ClusterDeposits6_3_C_fu_1006_p3;
    ap_return_70 <= ap_port_reg_ClusterPhi_10_read;
    ap_return_71 <= ap_port_reg_ClusterPhi_11_read;
    ap_return_72 <= ClusterPhi_12_read_s_fu_498_p1;
    ap_return_73 <= ClusterPhi_13_read_s_fu_494_p1;
    ap_return_74 <= ap_port_reg_ClusterPhi_14_read;
    ap_return_75 <= ap_port_reg_ClusterPhi_15_read;
    ap_return_76 <= ap_const_lv16_0;
    ap_return_77 <= ap_const_lv16_0;
    ap_return_78 <= ap_const_lv16_0;
    ap_return_79 <= ap_const_lv16_0;
    ap_return_8 <= ClusterDeposits9_3_C_fu_1050_p3;
    ap_return_80 <= ap_const_lv16_0;
    ap_return_81 <= ap_const_lv16_0;
    ap_return_82 <= ap_const_lv16_0;
    ap_return_83 <= ap_const_lv16_0;
    ap_return_84 <= ap_const_lv16_0;
    ap_return_85 <= ap_const_lv16_0;
    ap_return_86 <= ap_const_lv16_0;
    ap_return_87 <= ap_const_lv16_0;
    ap_return_88 <= ap_const_lv16_0;
    ap_return_89 <= ap_const_lv16_0;
    ap_return_9 <= ClusterDeposits8_3_C_fu_1056_p3;
    p_read1_read9_fu_380_p3 <= 
        ClusterDeposits_1_r when (tmp_342_1_fu_366_p2(0) = '1') else 
        ClusterDeposits_9_r;
    p_read32_read_fu_517_p3 <= 
        ap_port_reg_ClusterEta_0_read when (tmp_s_reg_1634(0) = '1') else 
        ap_port_reg_ClusterEta_8_read;
    p_read33_read_fu_545_p3 <= 
        ap_port_reg_ClusterEta_1_read when (tmp_342_1_reg_1656(0) = '1') else 
        ap_port_reg_ClusterEta_9_read;
    p_read40_read_fu_510_p3 <= 
        ap_port_reg_ClusterEta_8_read when (tmp_s_reg_1634(0) = '1') else 
        ap_port_reg_ClusterEta_0_read;
    p_read41_read_fu_538_p3 <= 
        ap_port_reg_ClusterEta_9_read when (tmp_342_1_reg_1656(0) = '1') else 
        ap_port_reg_ClusterEta_1_read;
    p_read64_read_fu_531_p3 <= 
        ap_port_reg_ClusterPhi_0_read when (tmp_s_reg_1634(0) = '1') else 
        ap_port_reg_ClusterPhi_8_read;
    p_read65_read_fu_559_p3 <= 
        ap_port_reg_ClusterPhi_1_read when (tmp_342_1_reg_1656(0) = '1') else 
        ap_port_reg_ClusterPhi_9_read;
    p_read72_read_fu_524_p3 <= 
        ap_port_reg_ClusterPhi_8_read when (tmp_s_reg_1634(0) = '1') else 
        ap_port_reg_ClusterPhi_0_read;
    p_read73_read_fu_552_p3 <= 
        ap_port_reg_ClusterPhi_9_read when (tmp_342_1_reg_1656(0) = '1') else 
        ap_port_reg_ClusterPhi_1_read;
    p_read8_read_fu_350_p3 <= 
        ClusterDeposits_8_r when (tmp_s_fu_344_p2(0) = '1') else 
        ClusterDeposits_0_r;
    p_read9_read1_fu_372_p3 <= 
        ClusterDeposits_9_r when (tmp_342_1_fu_366_p2(0) = '1') else 
        ClusterDeposits_1_r;
    p_read_read8_fu_358_p3 <= 
        ClusterDeposits_0_r when (tmp_s_fu_344_p2(0) = '1') else 
        ClusterDeposits_8_r;
    tmp_342_1_fu_366_p2 <= "1" when (unsigned(ClusterDeposits_1_r) < unsigned(ClusterDeposits_9_r)) else "0";
    tmp_350_1_fu_407_p2 <= "1" when (unsigned(p_read9_read1_reg_1664) < unsigned(ap_port_reg_ClusterDeposits_5_r)) else "0";
    tmp_350_2_fu_426_p2 <= "1" when (unsigned(ap_port_reg_ClusterDeposits_2_r) < unsigned(ap_port_reg_ClusterDeposits_6_r)) else "0";
    tmp_350_3_fu_448_p2 <= "1" when (unsigned(ap_port_reg_ClusterDeposits_3_r) < unsigned(ap_port_reg_ClusterDeposits_7_r)) else "0";
    tmp_367_1_fu_482_p2 <= "1" when (unsigned(ClusterDeposits_1_Cl_fu_400_p3) < unsigned(ClusterDeposits2_1_C_fu_440_p3)) else "0";
    tmp_372_1_fu_488_p2 <= "1" when (unsigned(ClusterDeposits12_1_s_fu_419_p3) < unsigned(ClusterDeposits3_1_C_fu_462_p3)) else "0";
    tmp_377_1_fu_884_p2 <= "1" when (unsigned(ClusterDeposits_2_Cl_fu_683_p3) < unsigned(ClusterDeposits12_2_s_fu_721_p3)) else "0";
    tmp_377_2_fu_938_p2 <= "1" when (unsigned(ClusterDeposits6_2_C_fu_754_p3) < unsigned(ClusterDeposits7_2_C_fu_792_p3)) else "0";
    tmp_377_3_fu_992_p2 <= "1" when (unsigned(ClusterDeposits4_2_C_fu_759_p3) < unsigned(ClusterDeposits5_2_C_fu_797_p3)) else "0";
    tmp_377_4_fu_1046_p2 <= "1" when (unsigned(p_read_read8_reg_1649) < unsigned(p_read1_read9_reg_1671)) else "0";
    tmp_40_fu_388_p2 <= "1" when (unsigned(p_read8_read_reg_1642) < unsigned(ap_port_reg_ClusterDeposits_4_r)) else "0";
    tmp_41_fu_470_p2 <= "1" when (unsigned(ClusterDeposits4_1_C_fu_393_p3) < unsigned(ClusterDeposits6_1_C_fu_432_p3)) else "0";
    tmp_42_fu_476_p2 <= "1" when (unsigned(ClusterDeposits5_1_C_fu_412_p3) < unsigned(ClusterDeposits7_1_C_fu_454_p3)) else "0";
    tmp_43_fu_830_p2 <= "1" when (unsigned(ClusterDeposits2_2_C_fu_678_p3) < unsigned(ClusterDeposits3_2_C_fu_716_p3)) else "0";
    tmp_s_fu_344_p2 <= "1" when (unsigned(ClusterDeposits_0_r) < unsigned(ClusterDeposits_8_r)) else "0";
end behav;
