// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bitonic16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ClusterDeposits_0_r,
        ClusterDeposits_1_r,
        ClusterDeposits_2_r,
        ClusterDeposits_3_r,
        ClusterDeposits_4_r,
        ClusterDeposits_5_r,
        ClusterDeposits_6_r,
        ClusterDeposits_7_r,
        ClusterDeposits_14_s,
        ClusterDeposits_15_s,
        ClusterEta_0_read,
        ClusterEta_1_read,
        ClusterEta_2_read,
        ClusterEta_3_read,
        ClusterEta_4_read,
        ClusterEta_5_read,
        ClusterEta_6_read,
        ClusterEta_7_read,
        ClusterEta_8_read,
        ClusterEta_9_read,
        ClusterEta_12_read,
        ClusterEta_13_read,
        ClusterEta_14_read,
        ClusterEta_15_read,
        ClusterPhi_0_read,
        ClusterPhi_1_read,
        ClusterPhi_2_read,
        ClusterPhi_3_read,
        ClusterPhi_4_read,
        ClusterPhi_5_read,
        ClusterPhi_6_read,
        ClusterPhi_7_read,
        ClusterPhi_8_read,
        ClusterPhi_9_read,
        ClusterPhi_12_read,
        ClusterPhi_13_read,
        ClusterPhi_14_read,
        ClusterPhi_15_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61,
        ap_return_62,
        ap_return_63,
        ap_return_64,
        ap_return_65,
        ap_return_66,
        ap_return_67,
        ap_return_68,
        ap_return_69,
        ap_return_70,
        ap_return_71,
        ap_return_72,
        ap_return_73,
        ap_return_74,
        ap_return_75,
        ap_return_76,
        ap_return_77,
        ap_return_78,
        ap_return_79,
        ap_return_80,
        ap_return_81,
        ap_return_82,
        ap_return_83,
        ap_return_84,
        ap_return_85,
        ap_return_86,
        ap_return_87,
        ap_return_88,
        ap_return_89
);

parameter    ap_ST_fsm_state1 = 6'b1;
parameter    ap_ST_fsm_state2 = 6'b10;
parameter    ap_ST_fsm_state3 = 6'b100;
parameter    ap_ST_fsm_state4 = 6'b1000;
parameter    ap_ST_fsm_state5 = 6'b10000;
parameter    ap_ST_fsm_state6 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_5 = 32'b101;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ClusterDeposits_0_r;
input  [15:0] ClusterDeposits_1_r;
input  [15:0] ClusterDeposits_2_r;
input  [15:0] ClusterDeposits_3_r;
input  [15:0] ClusterDeposits_4_r;
input  [15:0] ClusterDeposits_5_r;
input  [15:0] ClusterDeposits_6_r;
input  [15:0] ClusterDeposits_7_r;
input  [15:0] ClusterDeposits_14_s;
input  [15:0] ClusterDeposits_15_s;
input  [15:0] ClusterEta_0_read;
input  [15:0] ClusterEta_1_read;
input  [15:0] ClusterEta_2_read;
input  [15:0] ClusterEta_3_read;
input  [15:0] ClusterEta_4_read;
input  [15:0] ClusterEta_5_read;
input  [15:0] ClusterEta_6_read;
input  [15:0] ClusterEta_7_read;
input  [15:0] ClusterEta_8_read;
input  [15:0] ClusterEta_9_read;
input  [0:0] ClusterEta_12_read;
input  [0:0] ClusterEta_13_read;
input  [15:0] ClusterEta_14_read;
input  [15:0] ClusterEta_15_read;
input  [15:0] ClusterPhi_0_read;
input  [15:0] ClusterPhi_1_read;
input  [15:0] ClusterPhi_2_read;
input  [15:0] ClusterPhi_3_read;
input  [15:0] ClusterPhi_4_read;
input  [15:0] ClusterPhi_5_read;
input  [15:0] ClusterPhi_6_read;
input  [15:0] ClusterPhi_7_read;
input  [15:0] ClusterPhi_8_read;
input  [15:0] ClusterPhi_9_read;
input  [0:0] ClusterPhi_12_read;
input  [0:0] ClusterPhi_13_read;
input  [15:0] ClusterPhi_14_read;
input  [15:0] ClusterPhi_15_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [15:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [15:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [15:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [15:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [15:0] ap_return_44;
output  [15:0] ap_return_45;
output  [15:0] ap_return_46;
output  [15:0] ap_return_47;
output  [15:0] ap_return_48;
output  [15:0] ap_return_49;
output  [15:0] ap_return_50;
output  [15:0] ap_return_51;
output  [15:0] ap_return_52;
output  [15:0] ap_return_53;
output  [15:0] ap_return_54;
output  [15:0] ap_return_55;
output  [15:0] ap_return_56;
output  [15:0] ap_return_57;
output  [15:0] ap_return_58;
output  [15:0] ap_return_59;
output  [15:0] ap_return_60;
output  [15:0] ap_return_61;
output  [15:0] ap_return_62;
output  [15:0] ap_return_63;
output  [15:0] ap_return_64;
output  [15:0] ap_return_65;
output  [15:0] ap_return_66;
output  [15:0] ap_return_67;
output  [15:0] ap_return_68;
output  [15:0] ap_return_69;
output  [15:0] ap_return_70;
output  [15:0] ap_return_71;
output  [15:0] ap_return_72;
output  [15:0] ap_return_73;
output  [15:0] ap_return_74;
output  [15:0] ap_return_75;
output  [15:0] ap_return_76;
output  [15:0] ap_return_77;
output  [15:0] ap_return_78;
output  [15:0] ap_return_79;
output  [15:0] ap_return_80;
output  [15:0] ap_return_81;
output  [15:0] ap_return_82;
output  [15:0] ap_return_83;
output  [15:0] ap_return_84;
output  [15:0] ap_return_85;
output  [15:0] ap_return_86;
output  [15:0] ap_return_87;
output  [15:0] ap_return_88;
output  [15:0] ap_return_89;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
wire   [0:0] tmp_379_6_fu_362_p2;
reg   [0:0] tmp_379_6_reg_1202;
wire   [15:0] p_read14_read6_fu_368_p3;
reg   [15:0] p_read14_read6_reg_1210;
wire   [15:0] p_read6_read_fu_376_p3;
reg   [15:0] p_read6_read_reg_1217;
wire   [0:0] tmp_379_7_fu_384_p2;
reg   [0:0] tmp_379_7_reg_1225;
wire   [15:0] p_read15_read7_fu_390_p3;
reg   [15:0] p_read15_read7_reg_1233;
wire   [15:0] p_read7_read_fu_398_p3;
reg   [15:0] p_read7_read_reg_1240;
wire   [0:0] tmp_s_fu_406_p2;
reg   [0:0] tmp_s_reg_1248;
wire   [0:0] ap_CS_fsm_state2;
wire   [15:0] p_read12_read4_read_fu_412_p3;
reg   [15:0] p_read12_read4_read_reg_1256;
wire   [15:0] p_read8_read_read_fu_420_p3;
reg   [15:0] p_read8_read_read_reg_1262;
wire   [0:0] tmp_387_1_fu_428_p2;
reg   [0:0] tmp_387_1_reg_1268;
wire   [15:0] ClusterDeposits5_0_C_fu_434_p3;
reg   [15:0] ClusterDeposits5_0_C_reg_1276;
wire   [15:0] ClusterDeposits12_0_s_fu_442_p3;
reg   [15:0] ClusterDeposits12_0_s_reg_1282;
wire   [0:0] tmp_387_2_fu_450_p2;
reg   [0:0] tmp_387_2_reg_1288;
wire   [15:0] ClusterDeposits6_0_C_fu_455_p3;
reg   [15:0] ClusterDeposits6_0_C_reg_1296;
wire   [15:0] ClusterDeposits2_0_C_fu_462_p3;
reg   [15:0] ClusterDeposits2_0_C_reg_1302;
wire   [0:0] tmp_387_3_fu_469_p2;
reg   [0:0] tmp_387_3_reg_1308;
wire   [15:0] p_read15_read7_Clust_fu_474_p3;
reg   [15:0] p_read15_read7_Clust_reg_1316;
wire   [15:0] ClusterDeposits3_0_s_fu_481_p3;
reg   [15:0] ClusterDeposits3_0_s_reg_1322;
wire   [0:0] tmp_44_fu_488_p2;
reg   [0:0] tmp_44_reg_1328;
wire   [0:0] tmp_45_fu_494_p2;
reg   [0:0] tmp_45_reg_1338;
wire   [0:0] tmp_404_1_fu_500_p2;
reg   [0:0] tmp_404_1_reg_1348;
wire   [0:0] tmp_409_1_fu_506_p2;
reg   [0:0] tmp_409_1_reg_1358;
wire   [15:0] ClusterEta41_0_Clust_fu_685_p3;
reg   [15:0] ClusterEta41_0_Clust_reg_1368;
wire   [0:0] ap_CS_fsm_state3;
wire   [15:0] ClusterPhi72_0_Clust_fu_693_p3;
reg   [15:0] ClusterPhi72_0_Clust_reg_1373;
wire   [15:0] ClusterEta42_0_read_fu_706_p3;
reg   [15:0] ClusterEta42_0_read_reg_1378;
wire   [15:0] ClusterPhi73_0_read_fu_714_p3;
reg   [15:0] ClusterPhi73_0_read_reg_1383;
wire   [15:0] ClusterEta39_1_Clust_fu_882_p3;
reg   [15:0] ClusterEta39_1_Clust_reg_1388;
wire   [15:0] ClusterPhi7078_1_Clu_fu_898_p3;
reg   [15:0] ClusterPhi7078_1_Clu_reg_1393;
wire   [15:0] ClusterEta40_1_read_fu_914_p3;
reg   [15:0] ClusterEta40_1_read_reg_1398;
wire   [15:0] ClusterPhi71_1_read_fu_930_p3;
reg   [15:0] ClusterPhi71_1_read_reg_1403;
wire   [15:0] sel_SEBB1_fu_944_p3;
reg   [15:0] sel_SEBB1_reg_1408;
wire   [15:0] sel_SEBB_fu_952_p3;
reg   [15:0] sel_SEBB_reg_1413;
wire   [15:0] ClusterEta34_1_Clust_1_fu_960_p3;
reg   [15:0] ClusterEta34_1_Clust_1_reg_1418;
wire   [15:0] ClusterEta_2_Cluster_fu_968_p3;
reg   [15:0] ClusterEta_2_Cluster_reg_1423;
wire   [15:0] ClusterPhi65_1_Clust_1_fu_976_p3;
reg   [15:0] ClusterPhi65_1_Clust_1_reg_1428;
wire   [15:0] ClusterPhi_2_Cluster_fu_984_p3;
reg   [15:0] ClusterPhi_2_Cluster_reg_1433;
wire   [15:0] ClusterDeposits3_2_C_fu_998_p3;
reg   [15:0] ClusterDeposits3_2_C_reg_1438;
wire   [15:0] ClusterDeposits2_2_C_fu_1006_p3;
reg   [15:0] ClusterDeposits2_2_C_reg_1443;
wire   [15:0] ClusterEta34_2_Clust_fu_1014_p3;
reg   [15:0] ClusterEta34_2_Clust_reg_1448;
wire   [15:0] ClusterEta33_2_Clust_fu_1022_p3;
reg   [15:0] ClusterEta33_2_Clust_reg_1453;
wire   [15:0] ClusterPhi65_2_Clust_fu_1030_p3;
reg   [15:0] ClusterPhi65_2_Clust_reg_1458;
wire   [15:0] ClusterPhi64_2_Clust_fu_1038_p3;
reg   [15:0] ClusterPhi64_2_Clust_reg_1463;
wire   [15:0] ClusterDeposits5_2_C_fu_1052_p3;
reg   [15:0] ClusterDeposits5_2_C_reg_1468;
wire   [15:0] ClusterDeposits4_2_C_fu_1060_p3;
reg   [15:0] ClusterDeposits4_2_C_reg_1473;
wire   [15:0] ClusterEta36_2_Clust_fu_1068_p3;
reg   [15:0] ClusterEta36_2_Clust_reg_1478;
wire   [15:0] ClusterEta35_2_Clust_fu_1076_p3;
reg   [15:0] ClusterEta35_2_Clust_reg_1483;
wire   [15:0] ClusterPhi67_2_Clust_fu_1084_p3;
reg   [15:0] ClusterPhi67_2_Clust_reg_1488;
wire   [15:0] ClusterPhi66_2_Clust_fu_1092_p3;
reg   [15:0] ClusterPhi66_2_Clust_reg_1493;
wire   [15:0] ClusterDeposits7_2_C_fu_1106_p3;
reg   [15:0] ClusterDeposits7_2_C_reg_1498;
wire   [15:0] ClusterDeposits6_2_C_fu_1114_p3;
reg   [15:0] ClusterDeposits6_2_C_reg_1503;
wire   [15:0] ClusterEta38_2_Clust_fu_1122_p3;
reg   [15:0] ClusterEta38_2_Clust_reg_1508;
wire   [15:0] ClusterEta3743_2_Clu_fu_1130_p3;
reg   [15:0] ClusterEta3743_2_Clu_reg_1513;
wire   [15:0] ClusterPhi69_2_Clust_fu_1138_p3;
reg   [15:0] ClusterPhi69_2_Clust_reg_1518;
wire   [15:0] ClusterPhi68_2_Clust_fu_1146_p3;
reg   [15:0] ClusterPhi68_2_Clust_reg_1523;
wire   [15:0] ClusterDeposits9_2_C_fu_1158_p3;
reg   [15:0] ClusterDeposits9_2_C_reg_1528;
wire   [15:0] ClusterDeposits8_2_C_fu_1164_p3;
reg   [15:0] ClusterDeposits8_2_C_reg_1533;
wire   [15:0] ClusterEta40_2_Clust_fu_1170_p3;
reg   [15:0] ClusterEta40_2_Clust_reg_1538;
wire   [15:0] ClusterEta39_2_Clust_fu_1178_p3;
reg   [15:0] ClusterEta39_2_Clust_reg_1543;
wire   [15:0] ClusterPhi71_2_Clust_fu_1186_p3;
reg   [15:0] ClusterPhi71_2_Clust_reg_1548;
wire   [15:0] ClusterPhi7078_2_Clu_fu_1194_p3;
reg   [15:0] ClusterPhi7078_2_Clu_reg_1553;
wire   [0:0] ap_CS_fsm_state4;
reg   [15:0] ap_port_reg_ClusterDeposits_0_r;
reg   [15:0] ap_port_reg_ClusterDeposits_1_r;
reg   [15:0] ap_port_reg_ClusterDeposits_2_r;
reg   [15:0] ap_port_reg_ClusterDeposits_3_r;
reg   [15:0] ap_port_reg_ClusterDeposits_4_r;
reg   [15:0] ap_port_reg_ClusterDeposits_5_r;
reg   [15:0] ap_port_reg_ClusterEta_0_read;
reg   [15:0] ap_port_reg_ClusterEta_1_read;
reg   [15:0] ap_port_reg_ClusterEta_2_read;
reg   [15:0] ap_port_reg_ClusterEta_3_read;
reg   [15:0] ap_port_reg_ClusterEta_4_read;
reg   [15:0] ap_port_reg_ClusterEta_5_read;
reg   [15:0] ap_port_reg_ClusterEta_6_read;
reg   [15:0] ap_port_reg_ClusterEta_7_read;
reg   [15:0] ap_port_reg_ClusterEta_8_read;
reg   [15:0] ap_port_reg_ClusterEta_9_read;
reg   [0:0] ap_port_reg_ClusterEta_12_read;
reg   [0:0] ap_port_reg_ClusterEta_13_read;
reg   [15:0] ap_port_reg_ClusterEta_14_read;
reg   [15:0] ap_port_reg_ClusterEta_15_read;
reg   [15:0] ap_port_reg_ClusterPhi_0_read;
reg   [15:0] ap_port_reg_ClusterPhi_1_read;
reg   [15:0] ap_port_reg_ClusterPhi_2_read;
reg   [15:0] ap_port_reg_ClusterPhi_3_read;
reg   [15:0] ap_port_reg_ClusterPhi_4_read;
reg   [15:0] ap_port_reg_ClusterPhi_5_read;
reg   [15:0] ap_port_reg_ClusterPhi_6_read;
reg   [15:0] ap_port_reg_ClusterPhi_7_read;
reg   [15:0] ap_port_reg_ClusterPhi_8_read;
reg   [15:0] ap_port_reg_ClusterPhi_9_read;
reg   [0:0] ap_port_reg_ClusterPhi_12_read;
reg   [0:0] ap_port_reg_ClusterPhi_13_read;
reg   [15:0] ap_port_reg_ClusterPhi_14_read;
reg   [15:0] ap_port_reg_ClusterPhi_15_read;
wire    grp_bitonic32_fu_312_ap_start;
wire    grp_bitonic32_fu_312_ap_done;
wire    grp_bitonic32_fu_312_ap_idle;
wire    grp_bitonic32_fu_312_ap_ready;
wire   [15:0] grp_bitonic32_fu_312_ap_return_0;
wire   [15:0] grp_bitonic32_fu_312_ap_return_1;
wire   [15:0] grp_bitonic32_fu_312_ap_return_2;
wire   [15:0] grp_bitonic32_fu_312_ap_return_3;
wire   [15:0] grp_bitonic32_fu_312_ap_return_4;
wire   [15:0] grp_bitonic32_fu_312_ap_return_5;
wire   [15:0] grp_bitonic32_fu_312_ap_return_6;
wire   [15:0] grp_bitonic32_fu_312_ap_return_7;
wire   [15:0] grp_bitonic32_fu_312_ap_return_8;
wire   [15:0] grp_bitonic32_fu_312_ap_return_9;
wire   [15:0] grp_bitonic32_fu_312_ap_return_10;
wire   [15:0] grp_bitonic32_fu_312_ap_return_11;
wire   [15:0] grp_bitonic32_fu_312_ap_return_12;
wire   [15:0] grp_bitonic32_fu_312_ap_return_13;
wire   [15:0] grp_bitonic32_fu_312_ap_return_14;
wire   [15:0] grp_bitonic32_fu_312_ap_return_15;
wire   [15:0] grp_bitonic32_fu_312_ap_return_16;
wire   [15:0] grp_bitonic32_fu_312_ap_return_17;
wire   [15:0] grp_bitonic32_fu_312_ap_return_18;
wire   [15:0] grp_bitonic32_fu_312_ap_return_19;
wire   [15:0] grp_bitonic32_fu_312_ap_return_20;
wire   [15:0] grp_bitonic32_fu_312_ap_return_21;
wire   [15:0] grp_bitonic32_fu_312_ap_return_22;
wire   [15:0] grp_bitonic32_fu_312_ap_return_23;
wire   [15:0] grp_bitonic32_fu_312_ap_return_24;
wire   [15:0] grp_bitonic32_fu_312_ap_return_25;
wire   [15:0] grp_bitonic32_fu_312_ap_return_26;
wire   [15:0] grp_bitonic32_fu_312_ap_return_27;
wire   [15:0] grp_bitonic32_fu_312_ap_return_28;
wire   [15:0] grp_bitonic32_fu_312_ap_return_29;
wire   [15:0] grp_bitonic32_fu_312_ap_return_30;
wire   [15:0] grp_bitonic32_fu_312_ap_return_31;
wire   [15:0] grp_bitonic32_fu_312_ap_return_32;
wire   [15:0] grp_bitonic32_fu_312_ap_return_33;
wire   [15:0] grp_bitonic32_fu_312_ap_return_34;
wire   [15:0] grp_bitonic32_fu_312_ap_return_35;
wire   [15:0] grp_bitonic32_fu_312_ap_return_36;
wire   [15:0] grp_bitonic32_fu_312_ap_return_37;
wire   [15:0] grp_bitonic32_fu_312_ap_return_38;
wire   [15:0] grp_bitonic32_fu_312_ap_return_39;
wire   [15:0] grp_bitonic32_fu_312_ap_return_40;
wire   [15:0] grp_bitonic32_fu_312_ap_return_41;
wire   [15:0] grp_bitonic32_fu_312_ap_return_42;
wire   [15:0] grp_bitonic32_fu_312_ap_return_43;
wire   [15:0] grp_bitonic32_fu_312_ap_return_44;
wire   [15:0] grp_bitonic32_fu_312_ap_return_45;
wire   [15:0] grp_bitonic32_fu_312_ap_return_46;
wire   [15:0] grp_bitonic32_fu_312_ap_return_47;
wire   [15:0] grp_bitonic32_fu_312_ap_return_48;
wire   [15:0] grp_bitonic32_fu_312_ap_return_49;
wire   [15:0] grp_bitonic32_fu_312_ap_return_50;
wire   [15:0] grp_bitonic32_fu_312_ap_return_51;
wire   [15:0] grp_bitonic32_fu_312_ap_return_52;
wire   [15:0] grp_bitonic32_fu_312_ap_return_53;
wire   [15:0] grp_bitonic32_fu_312_ap_return_54;
wire   [15:0] grp_bitonic32_fu_312_ap_return_55;
wire   [15:0] grp_bitonic32_fu_312_ap_return_56;
wire   [15:0] grp_bitonic32_fu_312_ap_return_57;
wire   [15:0] grp_bitonic32_fu_312_ap_return_58;
wire   [15:0] grp_bitonic32_fu_312_ap_return_59;
wire   [15:0] grp_bitonic32_fu_312_ap_return_60;
wire   [15:0] grp_bitonic32_fu_312_ap_return_61;
wire   [15:0] grp_bitonic32_fu_312_ap_return_62;
wire   [15:0] grp_bitonic32_fu_312_ap_return_63;
wire   [15:0] grp_bitonic32_fu_312_ap_return_64;
wire   [15:0] grp_bitonic32_fu_312_ap_return_65;
wire   [15:0] grp_bitonic32_fu_312_ap_return_66;
wire   [15:0] grp_bitonic32_fu_312_ap_return_67;
wire   [15:0] grp_bitonic32_fu_312_ap_return_68;
wire   [15:0] grp_bitonic32_fu_312_ap_return_69;
wire   [15:0] grp_bitonic32_fu_312_ap_return_70;
wire   [15:0] grp_bitonic32_fu_312_ap_return_71;
wire   [15:0] grp_bitonic32_fu_312_ap_return_72;
wire   [15:0] grp_bitonic32_fu_312_ap_return_73;
wire   [15:0] grp_bitonic32_fu_312_ap_return_74;
wire   [15:0] grp_bitonic32_fu_312_ap_return_75;
wire   [15:0] grp_bitonic32_fu_312_ap_return_76;
wire   [15:0] grp_bitonic32_fu_312_ap_return_77;
wire   [15:0] grp_bitonic32_fu_312_ap_return_78;
wire   [15:0] grp_bitonic32_fu_312_ap_return_79;
wire   [15:0] grp_bitonic32_fu_312_ap_return_80;
wire   [15:0] grp_bitonic32_fu_312_ap_return_81;
wire   [15:0] grp_bitonic32_fu_312_ap_return_82;
wire   [15:0] grp_bitonic32_fu_312_ap_return_83;
wire   [15:0] grp_bitonic32_fu_312_ap_return_84;
wire   [15:0] grp_bitonic32_fu_312_ap_return_85;
wire   [15:0] grp_bitonic32_fu_312_ap_return_86;
wire   [15:0] grp_bitonic32_fu_312_ap_return_87;
wire   [15:0] grp_bitonic32_fu_312_ap_return_88;
wire   [15:0] grp_bitonic32_fu_312_ap_return_89;
reg    ap_reg_grp_bitonic32_fu_312_ap_start;
reg   [5:0] ap_NS_fsm;
wire   [0:0] ap_NS_fsm_state4;
wire   [15:0] p_read46_read_fu_512_p3;
wire   [15:0] p_read78_read_fu_526_p3;
wire   [15:0] p_read47_read_fu_540_p3;
wire   [15:0] p_read79_read_fu_554_p3;
wire   [0:0] tmp_391_2_fu_680_p2;
wire   [15:0] p_read38_read_fu_519_p3;
wire   [15:0] p_read70_read_fu_533_p3;
wire   [0:0] tmp_391_3_fu_701_p2;
wire   [15:0] p_read39_read_fu_547_p3;
wire   [15:0] p_read71_read_fu_561_p3;
wire   [15:0] ClusterEta3743_0_Clu_fu_624_p3;
wire   [15:0] p_read44_read36_rea_fu_568_p3;
wire   [15:0] ClusterPhi68_0_Clust_fu_638_p3;
wire   [15:0] p_read76_read68_rea_fu_582_p3;
wire   [15:0] p_read47_read39_Clus_fu_652_p3;
wire   [15:0] ClusterEta36_0_Clust_fu_596_p3;
wire   [15:0] p_read79_read71_Clus_fu_666_p3;
wire   [15:0] ClusterPhi67_0_Clust_fu_610_p3;
wire   [15:0] ClusterEta33_0_Clust_fu_631_p3;
wire   [15:0] p_read40_read32_rea_fu_575_p3;
wire   [15:0] ClusterPhi64_0_Clust_fu_645_p3;
wire   [15:0] p_read72_read64_rea_fu_589_p3;
wire   [15:0] ClusterEta34_0_read_fu_659_p3;
wire   [15:0] ClusterEta32_0_Clust_fu_603_p3;
wire   [15:0] ClusterPhi65_0_read_fu_673_p3;
wire   [15:0] ClusterPhi63_0_Clust_fu_617_p3;
wire   [15:0] sel_SEBB7_fu_722_p3;
wire   [15:0] ClusterDeposits3_1_C_fu_760_p3;
wire   [0:0] tmp_46_fu_938_p2;
wire   [15:0] ClusterEta34_1_Clust_fu_770_p3;
wire   [15:0] ClusterEta3743_0_Clu_1_fu_732_p3;
wire   [15:0] ClusterPhi65_1_Clust_fu_784_p3;
wire   [15:0] ClusterPhi68_0_Clust_1_fu_746_p3;
wire   [15:0] sel_SEBB8_fu_727_p3;
wire   [15:0] ClusterDeposits12_1_s_fu_765_p3;
wire   [0:0] tmp_424_1_fu_992_p2;
wire   [15:0] ClusterEta32_1_Clust_fu_777_p3;
wire   [15:0] ClusterEta_1_Cluster_fu_739_p3;
wire   [15:0] ClusterPhi63_1_Clust_fu_791_p3;
wire   [15:0] ClusterPhi_1_Cluster_fu_753_p3;
wire   [15:0] ClusterDeposits6_1_C_fu_798_p3;
wire   [15:0] ClusterDeposits7_1_C_fu_836_p3;
wire   [0:0] tmp_424_2_fu_1046_p2;
wire   [15:0] ClusterEta38_1_Clust_fu_846_p3;
wire   [15:0] ClusterEta3743_1_Clu_fu_808_p3;
wire   [15:0] ClusterPhi69_1_Clust_fu_860_p3;
wire   [15:0] ClusterPhi68_1_Clust_fu_822_p3;
wire   [15:0] ClusterDeposits4_1_C_fu_803_p3;
wire   [15:0] ClusterDeposits5_1_C_fu_841_p3;
wire   [0:0] tmp_424_3_fu_1100_p2;
wire   [15:0] ClusterEta36_1_Clust_fu_853_p3;
wire   [15:0] ClusterEta35_1_Clust_fu_815_p3;
wire   [15:0] ClusterPhi67_1_Clust_fu_867_p3;
wire   [15:0] ClusterPhi66_1_Clust_fu_829_p3;
wire   [0:0] tmp_424_4_fu_1154_p2;
wire   [15:0] p_read39_read47_Clus_fu_906_p3;
wire   [15:0] ClusterEta41_1_Clust_fu_874_p3;
wire   [15:0] p_read71_read79_Clus_fu_922_p3;
wire   [15:0] ClusterPhi72_1_Clust_fu_890_p3;
wire   [0:0] ap_CS_fsm_state6;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'b1;
#0 ap_reg_grp_bitonic32_fu_312_ap_start = 1'b0;
end

bitonic32 grp_bitonic32_fu_312(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bitonic32_fu_312_ap_start),
    .ap_done(grp_bitonic32_fu_312_ap_done),
    .ap_idle(grp_bitonic32_fu_312_ap_idle),
    .ap_ready(grp_bitonic32_fu_312_ap_ready),
    .ClusterDeposits_0_r(sel_SEBB1_reg_1408),
    .ClusterDeposits_1_r(sel_SEBB_reg_1413),
    .ClusterDeposits_2_r(ClusterDeposits3_2_C_reg_1438),
    .ClusterDeposits_3_r(ClusterDeposits2_2_C_reg_1443),
    .ClusterDeposits_4_r(ClusterDeposits5_2_C_reg_1468),
    .ClusterDeposits_5_r(ClusterDeposits4_2_C_reg_1473),
    .ClusterDeposits_6_r(ClusterDeposits7_2_C_reg_1498),
    .ClusterDeposits_7_r(ClusterDeposits6_2_C_reg_1503),
    .ClusterDeposits_8_r(ClusterDeposits9_2_C_reg_1528),
    .ClusterDeposits_9_r(ClusterDeposits8_2_C_reg_1533),
    .ClusterEta_0_read(ClusterEta34_1_Clust_1_reg_1418),
    .ClusterEta_1_read(ClusterEta_2_Cluster_reg_1423),
    .ClusterEta_2_read(ClusterEta34_2_Clust_reg_1448),
    .ClusterEta_3_read(ClusterEta33_2_Clust_reg_1453),
    .ClusterEta_4_read(ClusterEta36_2_Clust_reg_1478),
    .ClusterEta_5_read(ClusterEta35_2_Clust_reg_1483),
    .ClusterEta_6_read(ClusterEta38_2_Clust_reg_1508),
    .ClusterEta_7_read(ClusterEta3743_2_Clu_reg_1513),
    .ClusterEta_8_read(ClusterEta40_2_Clust_reg_1538),
    .ClusterEta_9_read(ClusterEta39_2_Clust_reg_1543),
    .ClusterEta_10_read(ClusterEta39_1_Clust_reg_1388),
    .ClusterEta_11_read(ClusterEta40_1_read_reg_1398),
    .ClusterEta_12_read(ap_port_reg_ClusterEta_12_read),
    .ClusterEta_13_read(ap_port_reg_ClusterEta_13_read),
    .ClusterEta_14_read(ClusterEta41_0_Clust_reg_1368),
    .ClusterEta_15_read(ClusterEta42_0_read_reg_1378),
    .ClusterPhi_0_read(ClusterPhi65_1_Clust_1_reg_1428),
    .ClusterPhi_1_read(ClusterPhi_2_Cluster_reg_1433),
    .ClusterPhi_2_read(ClusterPhi65_2_Clust_reg_1458),
    .ClusterPhi_3_read(ClusterPhi64_2_Clust_reg_1463),
    .ClusterPhi_4_read(ClusterPhi67_2_Clust_reg_1488),
    .ClusterPhi_5_read(ClusterPhi66_2_Clust_reg_1493),
    .ClusterPhi_6_read(ClusterPhi69_2_Clust_reg_1518),
    .ClusterPhi_7_read(ClusterPhi68_2_Clust_reg_1523),
    .ClusterPhi_8_read(ClusterPhi71_2_Clust_reg_1548),
    .ClusterPhi_9_read(ClusterPhi7078_2_Clu_reg_1553),
    .ClusterPhi_10_read(ClusterPhi7078_1_Clu_reg_1393),
    .ClusterPhi_11_read(ClusterPhi71_1_read_reg_1403),
    .ClusterPhi_12_read(ap_port_reg_ClusterPhi_12_read),
    .ClusterPhi_13_read(ap_port_reg_ClusterPhi_13_read),
    .ClusterPhi_14_read(ClusterPhi72_0_Clust_reg_1373),
    .ClusterPhi_15_read(ClusterPhi73_0_read_reg_1383),
    .ap_return_0(grp_bitonic32_fu_312_ap_return_0),
    .ap_return_1(grp_bitonic32_fu_312_ap_return_1),
    .ap_return_2(grp_bitonic32_fu_312_ap_return_2),
    .ap_return_3(grp_bitonic32_fu_312_ap_return_3),
    .ap_return_4(grp_bitonic32_fu_312_ap_return_4),
    .ap_return_5(grp_bitonic32_fu_312_ap_return_5),
    .ap_return_6(grp_bitonic32_fu_312_ap_return_6),
    .ap_return_7(grp_bitonic32_fu_312_ap_return_7),
    .ap_return_8(grp_bitonic32_fu_312_ap_return_8),
    .ap_return_9(grp_bitonic32_fu_312_ap_return_9),
    .ap_return_10(grp_bitonic32_fu_312_ap_return_10),
    .ap_return_11(grp_bitonic32_fu_312_ap_return_11),
    .ap_return_12(grp_bitonic32_fu_312_ap_return_12),
    .ap_return_13(grp_bitonic32_fu_312_ap_return_13),
    .ap_return_14(grp_bitonic32_fu_312_ap_return_14),
    .ap_return_15(grp_bitonic32_fu_312_ap_return_15),
    .ap_return_16(grp_bitonic32_fu_312_ap_return_16),
    .ap_return_17(grp_bitonic32_fu_312_ap_return_17),
    .ap_return_18(grp_bitonic32_fu_312_ap_return_18),
    .ap_return_19(grp_bitonic32_fu_312_ap_return_19),
    .ap_return_20(grp_bitonic32_fu_312_ap_return_20),
    .ap_return_21(grp_bitonic32_fu_312_ap_return_21),
    .ap_return_22(grp_bitonic32_fu_312_ap_return_22),
    .ap_return_23(grp_bitonic32_fu_312_ap_return_23),
    .ap_return_24(grp_bitonic32_fu_312_ap_return_24),
    .ap_return_25(grp_bitonic32_fu_312_ap_return_25),
    .ap_return_26(grp_bitonic32_fu_312_ap_return_26),
    .ap_return_27(grp_bitonic32_fu_312_ap_return_27),
    .ap_return_28(grp_bitonic32_fu_312_ap_return_28),
    .ap_return_29(grp_bitonic32_fu_312_ap_return_29),
    .ap_return_30(grp_bitonic32_fu_312_ap_return_30),
    .ap_return_31(grp_bitonic32_fu_312_ap_return_31),
    .ap_return_32(grp_bitonic32_fu_312_ap_return_32),
    .ap_return_33(grp_bitonic32_fu_312_ap_return_33),
    .ap_return_34(grp_bitonic32_fu_312_ap_return_34),
    .ap_return_35(grp_bitonic32_fu_312_ap_return_35),
    .ap_return_36(grp_bitonic32_fu_312_ap_return_36),
    .ap_return_37(grp_bitonic32_fu_312_ap_return_37),
    .ap_return_38(grp_bitonic32_fu_312_ap_return_38),
    .ap_return_39(grp_bitonic32_fu_312_ap_return_39),
    .ap_return_40(grp_bitonic32_fu_312_ap_return_40),
    .ap_return_41(grp_bitonic32_fu_312_ap_return_41),
    .ap_return_42(grp_bitonic32_fu_312_ap_return_42),
    .ap_return_43(grp_bitonic32_fu_312_ap_return_43),
    .ap_return_44(grp_bitonic32_fu_312_ap_return_44),
    .ap_return_45(grp_bitonic32_fu_312_ap_return_45),
    .ap_return_46(grp_bitonic32_fu_312_ap_return_46),
    .ap_return_47(grp_bitonic32_fu_312_ap_return_47),
    .ap_return_48(grp_bitonic32_fu_312_ap_return_48),
    .ap_return_49(grp_bitonic32_fu_312_ap_return_49),
    .ap_return_50(grp_bitonic32_fu_312_ap_return_50),
    .ap_return_51(grp_bitonic32_fu_312_ap_return_51),
    .ap_return_52(grp_bitonic32_fu_312_ap_return_52),
    .ap_return_53(grp_bitonic32_fu_312_ap_return_53),
    .ap_return_54(grp_bitonic32_fu_312_ap_return_54),
    .ap_return_55(grp_bitonic32_fu_312_ap_return_55),
    .ap_return_56(grp_bitonic32_fu_312_ap_return_56),
    .ap_return_57(grp_bitonic32_fu_312_ap_return_57),
    .ap_return_58(grp_bitonic32_fu_312_ap_return_58),
    .ap_return_59(grp_bitonic32_fu_312_ap_return_59),
    .ap_return_60(grp_bitonic32_fu_312_ap_return_60),
    .ap_return_61(grp_bitonic32_fu_312_ap_return_61),
    .ap_return_62(grp_bitonic32_fu_312_ap_return_62),
    .ap_return_63(grp_bitonic32_fu_312_ap_return_63),
    .ap_return_64(grp_bitonic32_fu_312_ap_return_64),
    .ap_return_65(grp_bitonic32_fu_312_ap_return_65),
    .ap_return_66(grp_bitonic32_fu_312_ap_return_66),
    .ap_return_67(grp_bitonic32_fu_312_ap_return_67),
    .ap_return_68(grp_bitonic32_fu_312_ap_return_68),
    .ap_return_69(grp_bitonic32_fu_312_ap_return_69),
    .ap_return_70(grp_bitonic32_fu_312_ap_return_70),
    .ap_return_71(grp_bitonic32_fu_312_ap_return_71),
    .ap_return_72(grp_bitonic32_fu_312_ap_return_72),
    .ap_return_73(grp_bitonic32_fu_312_ap_return_73),
    .ap_return_74(grp_bitonic32_fu_312_ap_return_74),
    .ap_return_75(grp_bitonic32_fu_312_ap_return_75),
    .ap_return_76(grp_bitonic32_fu_312_ap_return_76),
    .ap_return_77(grp_bitonic32_fu_312_ap_return_77),
    .ap_return_78(grp_bitonic32_fu_312_ap_return_78),
    .ap_return_79(grp_bitonic32_fu_312_ap_return_79),
    .ap_return_80(grp_bitonic32_fu_312_ap_return_80),
    .ap_return_81(grp_bitonic32_fu_312_ap_return_81),
    .ap_return_82(grp_bitonic32_fu_312_ap_return_82),
    .ap_return_83(grp_bitonic32_fu_312_ap_return_83),
    .ap_return_84(grp_bitonic32_fu_312_ap_return_84),
    .ap_return_85(grp_bitonic32_fu_312_ap_return_85),
    .ap_return_86(grp_bitonic32_fu_312_ap_return_86),
    .ap_return_87(grp_bitonic32_fu_312_ap_return_87),
    .ap_return_88(grp_bitonic32_fu_312_ap_return_88),
    .ap_return_89(grp_bitonic32_fu_312_ap_return_89)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_bitonic32_fu_312_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (1'b1 == ap_NS_fsm_state4))) begin
            ap_reg_grp_bitonic32_fu_312_ap_start <= 1'b1;
        end else if ((1'b1 == grp_bitonic32_fu_312_ap_ready)) begin
            ap_reg_grp_bitonic32_fu_312_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ClusterDeposits12_0_s_reg_1282 <= ClusterDeposits12_0_s_fu_442_p3;
        ClusterDeposits2_0_C_reg_1302 <= ClusterDeposits2_0_C_fu_462_p3;
        ClusterDeposits3_0_s_reg_1322 <= ClusterDeposits3_0_s_fu_481_p3;
        ClusterDeposits5_0_C_reg_1276 <= ClusterDeposits5_0_C_fu_434_p3;
        ClusterDeposits6_0_C_reg_1296 <= ClusterDeposits6_0_C_fu_455_p3;
        p_read12_read4_read_reg_1256 <= p_read12_read4_read_fu_412_p3;
        p_read15_read7_Clust_reg_1316 <= p_read15_read7_Clust_fu_474_p3;
        p_read8_read_read_reg_1262 <= p_read8_read_read_fu_420_p3;
        tmp_387_1_reg_1268 <= tmp_387_1_fu_428_p2;
        tmp_387_2_reg_1288 <= tmp_387_2_fu_450_p2;
        tmp_387_3_reg_1308 <= tmp_387_3_fu_469_p2;
        tmp_404_1_reg_1348 <= tmp_404_1_fu_500_p2;
        tmp_409_1_reg_1358 <= tmp_409_1_fu_506_p2;
        tmp_44_reg_1328 <= tmp_44_fu_488_p2;
        tmp_45_reg_1338 <= tmp_45_fu_494_p2;
        tmp_s_reg_1248 <= tmp_s_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ClusterDeposits2_2_C_reg_1443 <= ClusterDeposits2_2_C_fu_1006_p3;
        ClusterDeposits3_2_C_reg_1438 <= ClusterDeposits3_2_C_fu_998_p3;
        ClusterDeposits4_2_C_reg_1473 <= ClusterDeposits4_2_C_fu_1060_p3;
        ClusterDeposits5_2_C_reg_1468 <= ClusterDeposits5_2_C_fu_1052_p3;
        ClusterDeposits6_2_C_reg_1503 <= ClusterDeposits6_2_C_fu_1114_p3;
        ClusterDeposits7_2_C_reg_1498 <= ClusterDeposits7_2_C_fu_1106_p3;
        ClusterDeposits8_2_C_reg_1533 <= ClusterDeposits8_2_C_fu_1164_p3;
        ClusterDeposits9_2_C_reg_1528 <= ClusterDeposits9_2_C_fu_1158_p3;
        ClusterEta33_2_Clust_reg_1453 <= ClusterEta33_2_Clust_fu_1022_p3;
        ClusterEta34_1_Clust_1_reg_1418 <= ClusterEta34_1_Clust_1_fu_960_p3;
        ClusterEta34_2_Clust_reg_1448 <= ClusterEta34_2_Clust_fu_1014_p3;
        ClusterEta35_2_Clust_reg_1483 <= ClusterEta35_2_Clust_fu_1076_p3;
        ClusterEta36_2_Clust_reg_1478 <= ClusterEta36_2_Clust_fu_1068_p3;
        ClusterEta3743_2_Clu_reg_1513 <= ClusterEta3743_2_Clu_fu_1130_p3;
        ClusterEta38_2_Clust_reg_1508 <= ClusterEta38_2_Clust_fu_1122_p3;
        ClusterEta39_1_Clust_reg_1388 <= ClusterEta39_1_Clust_fu_882_p3;
        ClusterEta39_2_Clust_reg_1543 <= ClusterEta39_2_Clust_fu_1178_p3;
        ClusterEta40_1_read_reg_1398 <= ClusterEta40_1_read_fu_914_p3;
        ClusterEta40_2_Clust_reg_1538 <= ClusterEta40_2_Clust_fu_1170_p3;
        ClusterEta41_0_Clust_reg_1368 <= ClusterEta41_0_Clust_fu_685_p3;
        ClusterEta42_0_read_reg_1378 <= ClusterEta42_0_read_fu_706_p3;
        ClusterEta_2_Cluster_reg_1423 <= ClusterEta_2_Cluster_fu_968_p3;
        ClusterPhi64_2_Clust_reg_1463 <= ClusterPhi64_2_Clust_fu_1038_p3;
        ClusterPhi65_1_Clust_1_reg_1428 <= ClusterPhi65_1_Clust_1_fu_976_p3;
        ClusterPhi65_2_Clust_reg_1458 <= ClusterPhi65_2_Clust_fu_1030_p3;
        ClusterPhi66_2_Clust_reg_1493 <= ClusterPhi66_2_Clust_fu_1092_p3;
        ClusterPhi67_2_Clust_reg_1488 <= ClusterPhi67_2_Clust_fu_1084_p3;
        ClusterPhi68_2_Clust_reg_1523 <= ClusterPhi68_2_Clust_fu_1146_p3;
        ClusterPhi69_2_Clust_reg_1518 <= ClusterPhi69_2_Clust_fu_1138_p3;
        ClusterPhi7078_1_Clu_reg_1393 <= ClusterPhi7078_1_Clu_fu_898_p3;
        ClusterPhi7078_2_Clu_reg_1553 <= ClusterPhi7078_2_Clu_fu_1194_p3;
        ClusterPhi71_1_read_reg_1403 <= ClusterPhi71_1_read_fu_930_p3;
        ClusterPhi71_2_Clust_reg_1548 <= ClusterPhi71_2_Clust_fu_1186_p3;
        ClusterPhi72_0_Clust_reg_1373 <= ClusterPhi72_0_Clust_fu_693_p3;
        ClusterPhi73_0_read_reg_1383 <= ClusterPhi73_0_read_fu_714_p3;
        ClusterPhi_2_Cluster_reg_1433 <= ClusterPhi_2_Cluster_fu_984_p3;
        sel_SEBB1_reg_1408 <= sel_SEBB1_fu_944_p3;
        sel_SEBB_reg_1413 <= sel_SEBB_fu_952_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        ap_port_reg_ClusterDeposits_0_r <= ClusterDeposits_0_r;
        ap_port_reg_ClusterDeposits_1_r <= ClusterDeposits_1_r;
        ap_port_reg_ClusterDeposits_2_r <= ClusterDeposits_2_r;
        ap_port_reg_ClusterDeposits_3_r <= ClusterDeposits_3_r;
        ap_port_reg_ClusterDeposits_4_r <= ClusterDeposits_4_r;
        ap_port_reg_ClusterDeposits_5_r <= ClusterDeposits_5_r;
        ap_port_reg_ClusterEta_0_read <= ClusterEta_0_read;
        ap_port_reg_ClusterEta_12_read <= ClusterEta_12_read;
        ap_port_reg_ClusterEta_13_read <= ClusterEta_13_read;
        ap_port_reg_ClusterEta_14_read <= ClusterEta_14_read;
        ap_port_reg_ClusterEta_15_read <= ClusterEta_15_read;
        ap_port_reg_ClusterEta_1_read <= ClusterEta_1_read;
        ap_port_reg_ClusterEta_2_read <= ClusterEta_2_read;
        ap_port_reg_ClusterEta_3_read <= ClusterEta_3_read;
        ap_port_reg_ClusterEta_4_read <= ClusterEta_4_read;
        ap_port_reg_ClusterEta_5_read <= ClusterEta_5_read;
        ap_port_reg_ClusterEta_6_read <= ClusterEta_6_read;
        ap_port_reg_ClusterEta_7_read <= ClusterEta_7_read;
        ap_port_reg_ClusterEta_8_read <= ClusterEta_8_read;
        ap_port_reg_ClusterEta_9_read <= ClusterEta_9_read;
        ap_port_reg_ClusterPhi_0_read <= ClusterPhi_0_read;
        ap_port_reg_ClusterPhi_12_read <= ClusterPhi_12_read;
        ap_port_reg_ClusterPhi_13_read <= ClusterPhi_13_read;
        ap_port_reg_ClusterPhi_14_read <= ClusterPhi_14_read;
        ap_port_reg_ClusterPhi_15_read <= ClusterPhi_15_read;
        ap_port_reg_ClusterPhi_1_read <= ClusterPhi_1_read;
        ap_port_reg_ClusterPhi_2_read <= ClusterPhi_2_read;
        ap_port_reg_ClusterPhi_3_read <= ClusterPhi_3_read;
        ap_port_reg_ClusterPhi_4_read <= ClusterPhi_4_read;
        ap_port_reg_ClusterPhi_5_read <= ClusterPhi_5_read;
        ap_port_reg_ClusterPhi_6_read <= ClusterPhi_6_read;
        ap_port_reg_ClusterPhi_7_read <= ClusterPhi_7_read;
        ap_port_reg_ClusterPhi_8_read <= ClusterPhi_8_read;
        ap_port_reg_ClusterPhi_9_read <= ClusterPhi_9_read;
        p_read14_read6_reg_1210 <= p_read14_read6_fu_368_p3;
        p_read15_read7_reg_1233 <= p_read15_read7_fu_390_p3;
        p_read6_read_reg_1217 <= p_read6_read_fu_376_p3;
        p_read7_read_reg_1240 <= p_read7_read_fu_398_p3;
        tmp_379_6_reg_1202 <= tmp_379_6_fu_362_p2;
        tmp_379_7_reg_1225 <= tmp_379_7_fu_384_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ClusterDeposits12_0_s_fu_442_p3 = ((tmp_387_1_fu_428_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_1_r : ap_port_reg_ClusterDeposits_5_r);

assign ClusterDeposits12_1_s_fu_765_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? ClusterDeposits5_0_C_reg_1276 : p_read15_read7_Clust_reg_1316);

assign ClusterDeposits2_0_C_fu_462_p3 = ((tmp_387_2_fu_450_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_2_r : p_read14_read6_reg_1210);

assign ClusterDeposits2_2_C_fu_1006_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? sel_SEBB8_fu_727_p3 : ClusterDeposits12_1_s_fu_765_p3);

assign ClusterDeposits3_0_s_fu_481_p3 = ((tmp_387_3_fu_469_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_3_r : p_read15_read7_reg_1233);

assign ClusterDeposits3_1_C_fu_760_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? p_read15_read7_Clust_reg_1316 : ClusterDeposits5_0_C_reg_1276);

assign ClusterDeposits3_2_C_fu_998_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? ClusterDeposits12_1_s_fu_765_p3 : sel_SEBB8_fu_727_p3);

assign ClusterDeposits4_1_C_fu_803_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? p_read8_read_read_reg_1262 : ClusterDeposits2_0_C_reg_1302);

assign ClusterDeposits4_2_C_fu_1060_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterDeposits6_1_C_fu_798_p3 : ClusterDeposits7_1_C_fu_836_p3);

assign ClusterDeposits5_0_C_fu_434_p3 = ((tmp_387_1_fu_428_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_5_r : ap_port_reg_ClusterDeposits_1_r);

assign ClusterDeposits5_1_C_fu_841_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterDeposits12_0_s_reg_1282 : ClusterDeposits3_0_s_reg_1322);

assign ClusterDeposits5_2_C_fu_1052_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterDeposits7_1_C_fu_836_p3 : ClusterDeposits6_1_C_fu_798_p3);

assign ClusterDeposits6_0_C_fu_455_p3 = ((tmp_387_2_fu_450_p2[0:0] === 1'b1) ? p_read14_read6_reg_1210 : ap_port_reg_ClusterDeposits_2_r);

assign ClusterDeposits6_1_C_fu_798_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? ClusterDeposits2_0_C_reg_1302 : p_read8_read_read_reg_1262);

assign ClusterDeposits6_2_C_fu_1114_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterDeposits4_1_C_fu_803_p3 : ClusterDeposits5_1_C_fu_841_p3);

assign ClusterDeposits7_1_C_fu_836_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterDeposits3_0_s_reg_1322 : ClusterDeposits12_0_s_reg_1282);

assign ClusterDeposits7_2_C_fu_1106_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterDeposits5_1_C_fu_841_p3 : ClusterDeposits4_1_C_fu_803_p3);

assign ClusterDeposits8_2_C_fu_1164_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? p_read6_read_reg_1217 : p_read7_read_reg_1240);

assign ClusterDeposits9_2_C_fu_1158_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? p_read7_read_reg_1240 : p_read6_read_reg_1217);

assign ClusterEta32_0_Clust_fu_603_p3 = ((tmp_387_1_reg_1268[0:0] === 1'b1) ? ap_port_reg_ClusterEta_1_read : ap_port_reg_ClusterEta_5_read);

assign ClusterEta32_1_Clust_fu_777_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? ClusterEta36_0_Clust_fu_596_p3 : p_read47_read39_Clus_fu_652_p3);

assign ClusterEta33_0_Clust_fu_631_p3 = ((tmp_387_2_reg_1288[0:0] === 1'b1) ? ap_port_reg_ClusterEta_2_read : p_read46_read_fu_512_p3);

assign ClusterEta33_2_Clust_fu_1022_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? ClusterEta_1_Cluster_fu_739_p3 : ClusterEta32_1_Clust_fu_777_p3);

assign ClusterEta34_0_read_fu_659_p3 = ((tmp_387_3_reg_1308[0:0] === 1'b1) ? ap_port_reg_ClusterEta_3_read : p_read47_read_fu_540_p3);

assign ClusterEta34_1_Clust_1_fu_960_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? ClusterEta34_1_Clust_fu_770_p3 : ClusterEta3743_0_Clu_1_fu_732_p3);

assign ClusterEta34_1_Clust_fu_770_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? p_read47_read39_Clus_fu_652_p3 : ClusterEta36_0_Clust_fu_596_p3);

assign ClusterEta34_2_Clust_fu_1014_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? ClusterEta32_1_Clust_fu_777_p3 : ClusterEta_1_Cluster_fu_739_p3);

assign ClusterEta35_1_Clust_fu_815_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? p_read40_read32_rea_fu_575_p3 : ClusterEta33_0_Clust_fu_631_p3);

assign ClusterEta35_2_Clust_fu_1076_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterEta3743_1_Clu_fu_808_p3 : ClusterEta38_1_Clust_fu_846_p3);

assign ClusterEta36_0_Clust_fu_596_p3 = ((tmp_387_1_reg_1268[0:0] === 1'b1) ? ap_port_reg_ClusterEta_5_read : ap_port_reg_ClusterEta_1_read);

assign ClusterEta36_1_Clust_fu_853_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterEta32_0_Clust_fu_603_p3 : ClusterEta34_0_read_fu_659_p3);

assign ClusterEta36_2_Clust_fu_1068_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterEta38_1_Clust_fu_846_p3 : ClusterEta3743_1_Clu_fu_808_p3);

assign ClusterEta3743_0_Clu_1_fu_732_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? ClusterEta3743_0_Clu_fu_624_p3 : p_read44_read36_rea_fu_568_p3);

assign ClusterEta3743_0_Clu_fu_624_p3 = ((tmp_387_2_reg_1288[0:0] === 1'b1) ? p_read46_read_fu_512_p3 : ap_port_reg_ClusterEta_2_read);

assign ClusterEta3743_1_Clu_fu_808_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? ClusterEta33_0_Clust_fu_631_p3 : p_read40_read32_rea_fu_575_p3);

assign ClusterEta3743_2_Clu_fu_1130_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterEta35_1_Clust_fu_815_p3 : ClusterEta36_1_Clust_fu_853_p3);

assign ClusterEta38_1_Clust_fu_846_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterEta34_0_read_fu_659_p3 : ClusterEta32_0_Clust_fu_603_p3);

assign ClusterEta38_2_Clust_fu_1122_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterEta36_1_Clust_fu_853_p3 : ClusterEta35_1_Clust_fu_815_p3);

assign ClusterEta39_1_Clust_fu_882_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? ap_port_reg_ClusterEta_8_read : ap_const_lv16_0);

assign ClusterEta39_2_Clust_fu_1178_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? ClusterEta41_1_Clust_fu_874_p3 : p_read39_read47_Clus_fu_906_p3);

assign ClusterEta40_1_read_fu_914_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? ap_port_reg_ClusterEta_9_read : ap_const_lv16_0);

assign ClusterEta40_2_Clust_fu_1170_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? p_read39_read47_Clus_fu_906_p3 : ClusterEta41_1_Clust_fu_874_p3);

assign ClusterEta41_0_Clust_fu_685_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? ap_const_lv16_0 : p_read38_read_fu_519_p3);

assign ClusterEta41_1_Clust_fu_874_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? p_read38_read_fu_519_p3 : ap_port_reg_ClusterEta_8_read);

assign ClusterEta42_0_read_fu_706_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? ap_const_lv16_0 : p_read39_read_fu_547_p3);

assign ClusterEta_1_Cluster_fu_739_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? p_read44_read36_rea_fu_568_p3 : ClusterEta3743_0_Clu_fu_624_p3);

assign ClusterEta_2_Cluster_fu_968_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? ClusterEta3743_0_Clu_1_fu_732_p3 : ClusterEta34_1_Clust_fu_770_p3);

assign ClusterPhi63_0_Clust_fu_617_p3 = ((tmp_387_1_reg_1268[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_1_read : ap_port_reg_ClusterPhi_5_read);

assign ClusterPhi63_1_Clust_fu_791_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? ClusterPhi67_0_Clust_fu_610_p3 : p_read79_read71_Clus_fu_666_p3);

assign ClusterPhi64_0_Clust_fu_645_p3 = ((tmp_387_2_reg_1288[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_2_read : p_read78_read_fu_526_p3);

assign ClusterPhi64_2_Clust_fu_1038_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? ClusterPhi_1_Cluster_fu_753_p3 : ClusterPhi63_1_Clust_fu_791_p3);

assign ClusterPhi65_0_read_fu_673_p3 = ((tmp_387_3_reg_1308[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_3_read : p_read79_read_fu_554_p3);

assign ClusterPhi65_1_Clust_1_fu_976_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? ClusterPhi65_1_Clust_fu_784_p3 : ClusterPhi68_0_Clust_1_fu_746_p3);

assign ClusterPhi65_1_Clust_fu_784_p3 = ((tmp_45_reg_1338[0:0] === 1'b1) ? p_read79_read71_Clus_fu_666_p3 : ClusterPhi67_0_Clust_fu_610_p3);

assign ClusterPhi65_2_Clust_fu_1030_p3 = ((tmp_424_1_fu_992_p2[0:0] === 1'b1) ? ClusterPhi63_1_Clust_fu_791_p3 : ClusterPhi_1_Cluster_fu_753_p3);

assign ClusterPhi66_1_Clust_fu_829_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? p_read72_read64_rea_fu_589_p3 : ClusterPhi64_0_Clust_fu_645_p3);

assign ClusterPhi66_2_Clust_fu_1092_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterPhi68_1_Clust_fu_822_p3 : ClusterPhi69_1_Clust_fu_860_p3);

assign ClusterPhi67_0_Clust_fu_610_p3 = ((tmp_387_1_reg_1268[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_5_read : ap_port_reg_ClusterPhi_1_read);

assign ClusterPhi67_1_Clust_fu_867_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterPhi63_0_Clust_fu_617_p3 : ClusterPhi65_0_read_fu_673_p3);

assign ClusterPhi67_2_Clust_fu_1084_p3 = ((tmp_424_2_fu_1046_p2[0:0] === 1'b1) ? ClusterPhi69_1_Clust_fu_860_p3 : ClusterPhi68_1_Clust_fu_822_p3);

assign ClusterPhi68_0_Clust_1_fu_746_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? ClusterPhi68_0_Clust_fu_638_p3 : p_read76_read68_rea_fu_582_p3);

assign ClusterPhi68_0_Clust_fu_638_p3 = ((tmp_387_2_reg_1288[0:0] === 1'b1) ? p_read78_read_fu_526_p3 : ap_port_reg_ClusterPhi_2_read);

assign ClusterPhi68_1_Clust_fu_822_p3 = ((tmp_404_1_reg_1348[0:0] === 1'b1) ? ClusterPhi64_0_Clust_fu_645_p3 : p_read72_read64_rea_fu_589_p3);

assign ClusterPhi68_2_Clust_fu_1146_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterPhi66_1_Clust_fu_829_p3 : ClusterPhi67_1_Clust_fu_867_p3);

assign ClusterPhi69_1_Clust_fu_860_p3 = ((tmp_409_1_reg_1358[0:0] === 1'b1) ? ClusterPhi65_0_read_fu_673_p3 : ClusterPhi63_0_Clust_fu_617_p3);

assign ClusterPhi69_2_Clust_fu_1138_p3 = ((tmp_424_3_fu_1100_p2[0:0] === 1'b1) ? ClusterPhi67_1_Clust_fu_867_p3 : ClusterPhi66_1_Clust_fu_829_p3);

assign ClusterPhi7078_1_Clu_fu_898_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_8_read : ap_const_lv16_0);

assign ClusterPhi7078_2_Clu_fu_1194_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? ClusterPhi72_1_Clust_fu_890_p3 : p_read71_read79_Clus_fu_922_p3);

assign ClusterPhi71_1_read_fu_930_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_9_read : ap_const_lv16_0);

assign ClusterPhi71_2_Clust_fu_1186_p3 = ((tmp_424_4_fu_1154_p2[0:0] === 1'b1) ? p_read71_read79_Clus_fu_922_p3 : ClusterPhi72_1_Clust_fu_890_p3);

assign ClusterPhi72_0_Clust_fu_693_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? ap_const_lv16_0 : p_read70_read_fu_533_p3);

assign ClusterPhi72_1_Clust_fu_890_p3 = ((tmp_391_2_fu_680_p2[0:0] === 1'b1) ? p_read70_read_fu_533_p3 : ap_port_reg_ClusterPhi_8_read);

assign ClusterPhi73_0_read_fu_714_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? ap_const_lv16_0 : p_read71_read_fu_561_p3);

assign ClusterPhi_1_Cluster_fu_753_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? p_read76_read68_rea_fu_582_p3 : ClusterPhi68_0_Clust_fu_638_p3);

assign ClusterPhi_2_Cluster_fu_984_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? ClusterPhi68_0_Clust_1_fu_746_p3 : ClusterPhi65_1_Clust_fu_784_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state6 = ap_CS_fsm[ap_const_lv32_5];

assign ap_NS_fsm_state4 = ap_NS_fsm[ap_const_lv32_3];

assign ap_return_0 = grp_bitonic32_fu_312_ap_return_0;

assign ap_return_1 = grp_bitonic32_fu_312_ap_return_1;

assign ap_return_10 = grp_bitonic32_fu_312_ap_return_10;

assign ap_return_11 = grp_bitonic32_fu_312_ap_return_11;

assign ap_return_12 = grp_bitonic32_fu_312_ap_return_12;

assign ap_return_13 = grp_bitonic32_fu_312_ap_return_13;

assign ap_return_14 = grp_bitonic32_fu_312_ap_return_14;

assign ap_return_15 = grp_bitonic32_fu_312_ap_return_15;

assign ap_return_16 = grp_bitonic32_fu_312_ap_return_16;

assign ap_return_17 = grp_bitonic32_fu_312_ap_return_17;

assign ap_return_18 = grp_bitonic32_fu_312_ap_return_18;

assign ap_return_19 = grp_bitonic32_fu_312_ap_return_19;

assign ap_return_2 = grp_bitonic32_fu_312_ap_return_2;

assign ap_return_20 = grp_bitonic32_fu_312_ap_return_20;

assign ap_return_21 = grp_bitonic32_fu_312_ap_return_21;

assign ap_return_22 = grp_bitonic32_fu_312_ap_return_22;

assign ap_return_23 = grp_bitonic32_fu_312_ap_return_23;

assign ap_return_24 = grp_bitonic32_fu_312_ap_return_24;

assign ap_return_25 = grp_bitonic32_fu_312_ap_return_25;

assign ap_return_26 = grp_bitonic32_fu_312_ap_return_26;

assign ap_return_27 = grp_bitonic32_fu_312_ap_return_27;

assign ap_return_28 = grp_bitonic32_fu_312_ap_return_28;

assign ap_return_29 = grp_bitonic32_fu_312_ap_return_29;

assign ap_return_3 = grp_bitonic32_fu_312_ap_return_3;

assign ap_return_30 = grp_bitonic32_fu_312_ap_return_30;

assign ap_return_31 = grp_bitonic32_fu_312_ap_return_31;

assign ap_return_32 = grp_bitonic32_fu_312_ap_return_32;

assign ap_return_33 = grp_bitonic32_fu_312_ap_return_33;

assign ap_return_34 = grp_bitonic32_fu_312_ap_return_34;

assign ap_return_35 = grp_bitonic32_fu_312_ap_return_35;

assign ap_return_36 = grp_bitonic32_fu_312_ap_return_36;

assign ap_return_37 = grp_bitonic32_fu_312_ap_return_37;

assign ap_return_38 = grp_bitonic32_fu_312_ap_return_38;

assign ap_return_39 = grp_bitonic32_fu_312_ap_return_39;

assign ap_return_4 = grp_bitonic32_fu_312_ap_return_4;

assign ap_return_40 = grp_bitonic32_fu_312_ap_return_40;

assign ap_return_41 = grp_bitonic32_fu_312_ap_return_41;

assign ap_return_42 = grp_bitonic32_fu_312_ap_return_42;

assign ap_return_43 = grp_bitonic32_fu_312_ap_return_43;

assign ap_return_44 = grp_bitonic32_fu_312_ap_return_44;

assign ap_return_45 = grp_bitonic32_fu_312_ap_return_45;

assign ap_return_46 = grp_bitonic32_fu_312_ap_return_46;

assign ap_return_47 = grp_bitonic32_fu_312_ap_return_47;

assign ap_return_48 = grp_bitonic32_fu_312_ap_return_48;

assign ap_return_49 = grp_bitonic32_fu_312_ap_return_49;

assign ap_return_5 = grp_bitonic32_fu_312_ap_return_5;

assign ap_return_50 = grp_bitonic32_fu_312_ap_return_50;

assign ap_return_51 = grp_bitonic32_fu_312_ap_return_51;

assign ap_return_52 = grp_bitonic32_fu_312_ap_return_52;

assign ap_return_53 = grp_bitonic32_fu_312_ap_return_53;

assign ap_return_54 = grp_bitonic32_fu_312_ap_return_54;

assign ap_return_55 = grp_bitonic32_fu_312_ap_return_55;

assign ap_return_56 = grp_bitonic32_fu_312_ap_return_56;

assign ap_return_57 = grp_bitonic32_fu_312_ap_return_57;

assign ap_return_58 = grp_bitonic32_fu_312_ap_return_58;

assign ap_return_59 = grp_bitonic32_fu_312_ap_return_59;

assign ap_return_6 = grp_bitonic32_fu_312_ap_return_6;

assign ap_return_60 = grp_bitonic32_fu_312_ap_return_60;

assign ap_return_61 = grp_bitonic32_fu_312_ap_return_61;

assign ap_return_62 = grp_bitonic32_fu_312_ap_return_62;

assign ap_return_63 = grp_bitonic32_fu_312_ap_return_63;

assign ap_return_64 = grp_bitonic32_fu_312_ap_return_64;

assign ap_return_65 = grp_bitonic32_fu_312_ap_return_65;

assign ap_return_66 = grp_bitonic32_fu_312_ap_return_66;

assign ap_return_67 = grp_bitonic32_fu_312_ap_return_67;

assign ap_return_68 = grp_bitonic32_fu_312_ap_return_68;

assign ap_return_69 = grp_bitonic32_fu_312_ap_return_69;

assign ap_return_7 = grp_bitonic32_fu_312_ap_return_7;

assign ap_return_70 = grp_bitonic32_fu_312_ap_return_70;

assign ap_return_71 = grp_bitonic32_fu_312_ap_return_71;

assign ap_return_72 = grp_bitonic32_fu_312_ap_return_72;

assign ap_return_73 = grp_bitonic32_fu_312_ap_return_73;

assign ap_return_74 = grp_bitonic32_fu_312_ap_return_74;

assign ap_return_75 = grp_bitonic32_fu_312_ap_return_75;

assign ap_return_76 = grp_bitonic32_fu_312_ap_return_76;

assign ap_return_77 = grp_bitonic32_fu_312_ap_return_77;

assign ap_return_78 = grp_bitonic32_fu_312_ap_return_78;

assign ap_return_79 = grp_bitonic32_fu_312_ap_return_79;

assign ap_return_8 = grp_bitonic32_fu_312_ap_return_8;

assign ap_return_80 = grp_bitonic32_fu_312_ap_return_80;

assign ap_return_81 = grp_bitonic32_fu_312_ap_return_81;

assign ap_return_82 = grp_bitonic32_fu_312_ap_return_82;

assign ap_return_83 = grp_bitonic32_fu_312_ap_return_83;

assign ap_return_84 = grp_bitonic32_fu_312_ap_return_84;

assign ap_return_85 = grp_bitonic32_fu_312_ap_return_85;

assign ap_return_86 = grp_bitonic32_fu_312_ap_return_86;

assign ap_return_87 = grp_bitonic32_fu_312_ap_return_87;

assign ap_return_88 = grp_bitonic32_fu_312_ap_return_88;

assign ap_return_89 = grp_bitonic32_fu_312_ap_return_89;

assign ap_return_9 = grp_bitonic32_fu_312_ap_return_9;

assign grp_bitonic32_fu_312_ap_start = ap_reg_grp_bitonic32_fu_312_ap_start;

assign p_read12_read4_read_fu_412_p3 = ((tmp_s_fu_406_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_4_r : ap_port_reg_ClusterDeposits_0_r);

assign p_read14_read6_fu_368_p3 = ((tmp_379_6_fu_362_p2[0:0] === 1'b1) ? ClusterDeposits_14_s : ClusterDeposits_6_r);

assign p_read15_read7_Clust_fu_474_p3 = ((tmp_387_3_fu_469_p2[0:0] === 1'b1) ? p_read15_read7_reg_1233 : ap_port_reg_ClusterDeposits_3_r);

assign p_read15_read7_fu_390_p3 = ((tmp_379_7_fu_384_p2[0:0] === 1'b1) ? ClusterDeposits_15_s : ClusterDeposits_7_r);

assign p_read38_read_fu_519_p3 = ((tmp_379_6_reg_1202[0:0] === 1'b1) ? ap_port_reg_ClusterEta_6_read : ap_port_reg_ClusterEta_14_read);

assign p_read39_read47_Clus_fu_906_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? p_read39_read_fu_547_p3 : ap_port_reg_ClusterEta_9_read);

assign p_read39_read_fu_547_p3 = ((tmp_379_7_reg_1225[0:0] === 1'b1) ? ap_port_reg_ClusterEta_7_read : ap_port_reg_ClusterEta_15_read);

assign p_read40_read32_rea_fu_575_p3 = ((tmp_s_reg_1248[0:0] === 1'b1) ? ap_port_reg_ClusterEta_0_read : ap_port_reg_ClusterEta_4_read);

assign p_read44_read36_rea_fu_568_p3 = ((tmp_s_reg_1248[0:0] === 1'b1) ? ap_port_reg_ClusterEta_4_read : ap_port_reg_ClusterEta_0_read);

assign p_read46_read_fu_512_p3 = ((tmp_379_6_reg_1202[0:0] === 1'b1) ? ap_port_reg_ClusterEta_14_read : ap_port_reg_ClusterEta_6_read);

assign p_read47_read39_Clus_fu_652_p3 = ((tmp_387_3_reg_1308[0:0] === 1'b1) ? p_read47_read_fu_540_p3 : ap_port_reg_ClusterEta_3_read);

assign p_read47_read_fu_540_p3 = ((tmp_379_7_reg_1225[0:0] === 1'b1) ? ap_port_reg_ClusterEta_15_read : ap_port_reg_ClusterEta_7_read);

assign p_read6_read_fu_376_p3 = ((tmp_379_6_fu_362_p2[0:0] === 1'b1) ? ClusterDeposits_6_r : ClusterDeposits_14_s);

assign p_read70_read_fu_533_p3 = ((tmp_379_6_reg_1202[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_6_read : ap_port_reg_ClusterPhi_14_read);

assign p_read71_read79_Clus_fu_922_p3 = ((tmp_391_3_fu_701_p2[0:0] === 1'b1) ? p_read71_read_fu_561_p3 : ap_port_reg_ClusterPhi_9_read);

assign p_read71_read_fu_561_p3 = ((tmp_379_7_reg_1225[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_7_read : ap_port_reg_ClusterPhi_15_read);

assign p_read72_read64_rea_fu_589_p3 = ((tmp_s_reg_1248[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_0_read : ap_port_reg_ClusterPhi_4_read);

assign p_read76_read68_rea_fu_582_p3 = ((tmp_s_reg_1248[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_4_read : ap_port_reg_ClusterPhi_0_read);

assign p_read78_read_fu_526_p3 = ((tmp_379_6_reg_1202[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_14_read : ap_port_reg_ClusterPhi_6_read);

assign p_read79_read71_Clus_fu_666_p3 = ((tmp_387_3_reg_1308[0:0] === 1'b1) ? p_read79_read_fu_554_p3 : ap_port_reg_ClusterPhi_3_read);

assign p_read79_read_fu_554_p3 = ((tmp_379_7_reg_1225[0:0] === 1'b1) ? ap_port_reg_ClusterPhi_15_read : ap_port_reg_ClusterPhi_7_read);

assign p_read7_read_fu_398_p3 = ((tmp_379_7_fu_384_p2[0:0] === 1'b1) ? ClusterDeposits_7_r : ClusterDeposits_15_s);

assign p_read8_read_read_fu_420_p3 = ((tmp_s_fu_406_p2[0:0] === 1'b1) ? ap_port_reg_ClusterDeposits_0_r : ap_port_reg_ClusterDeposits_4_r);

assign sel_SEBB1_fu_944_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? ClusterDeposits3_1_C_fu_760_p3 : sel_SEBB7_fu_722_p3);

assign sel_SEBB7_fu_722_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? ClusterDeposits6_0_C_reg_1296 : p_read12_read4_read_reg_1256);

assign sel_SEBB8_fu_727_p3 = ((tmp_44_reg_1328[0:0] === 1'b1) ? p_read12_read4_read_reg_1256 : ClusterDeposits6_0_C_reg_1296);

assign sel_SEBB_fu_952_p3 = ((tmp_46_fu_938_p2[0:0] === 1'b1) ? sel_SEBB7_fu_722_p3 : ClusterDeposits3_1_C_fu_760_p3);

assign tmp_379_6_fu_362_p2 = ((ClusterDeposits_6_r < ClusterDeposits_14_s) ? 1'b1 : 1'b0);

assign tmp_379_7_fu_384_p2 = ((ClusterDeposits_7_r < ClusterDeposits_15_s) ? 1'b1 : 1'b0);

assign tmp_387_1_fu_428_p2 = ((ap_port_reg_ClusterDeposits_1_r < ap_port_reg_ClusterDeposits_5_r) ? 1'b1 : 1'b0);

assign tmp_387_2_fu_450_p2 = ((p_read14_read6_reg_1210 > ap_port_reg_ClusterDeposits_2_r) ? 1'b1 : 1'b0);

assign tmp_387_3_fu_469_p2 = ((p_read15_read7_reg_1233 > ap_port_reg_ClusterDeposits_3_r) ? 1'b1 : 1'b0);

assign tmp_391_2_fu_680_p2 = ((p_read6_read_reg_1217 != ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_391_3_fu_701_p2 = ((p_read7_read_reg_1240 != ap_const_lv16_0) ? 1'b1 : 1'b0);

assign tmp_404_1_fu_500_p2 = ((p_read8_read_read_fu_420_p3 < ClusterDeposits2_0_C_fu_462_p3) ? 1'b1 : 1'b0);

assign tmp_409_1_fu_506_p2 = ((ClusterDeposits12_0_s_fu_442_p3 < ClusterDeposits3_0_s_fu_481_p3) ? 1'b1 : 1'b0);

assign tmp_424_1_fu_992_p2 = ((sel_SEBB8_fu_727_p3 < ClusterDeposits12_1_s_fu_765_p3) ? 1'b1 : 1'b0);

assign tmp_424_2_fu_1046_p2 = ((ClusterDeposits6_1_C_fu_798_p3 < ClusterDeposits7_1_C_fu_836_p3) ? 1'b1 : 1'b0);

assign tmp_424_3_fu_1100_p2 = ((ClusterDeposits4_1_C_fu_803_p3 < ClusterDeposits5_1_C_fu_841_p3) ? 1'b1 : 1'b0);

assign tmp_424_4_fu_1154_p2 = ((p_read6_read_reg_1217 < p_read7_read_reg_1240) ? 1'b1 : 1'b0);

assign tmp_44_fu_488_p2 = ((p_read12_read4_read_fu_412_p3 < ClusterDeposits6_0_C_fu_455_p3) ? 1'b1 : 1'b0);

assign tmp_45_fu_494_p2 = ((ClusterDeposits5_0_C_fu_434_p3 < p_read15_read7_Clust_fu_474_p3) ? 1'b1 : 1'b0);

assign tmp_46_fu_938_p2 = ((sel_SEBB7_fu_722_p3 < ClusterDeposits3_1_C_fu_760_p3) ? 1'b1 : 1'b0);

assign tmp_s_fu_406_p2 = ((ap_port_reg_ClusterDeposits_0_r < ap_port_reg_ClusterDeposits_4_r) ? 1'b1 : 1'b0);

endmodule //bitonic16
